[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hien078/applied-mathematics-foundation/blob/master/linear_algebra/02_linear_maps_and_matrix_transformations/exercises.ipynb)

# Module 02 — Exercises: Linear Maps and Matrix Transformations

Forty-six solved problems in four tiers. Every problem carries a statement, a one-line intuition,
a stepwise solution, a boxed answer, a key takeaway, and — wherever the answer is numeric or
algorithmic — a code cell that recomputes it.

Theorem, proof and example numbers refer to
[first_principles.ipynb](first_principles.ipynb). Symbols follow
[the notation register](../../docs/notation.md): vectors are columns, the transpose is
$A^{\top}$, and norms are written $\lVert x \rVert$.

The preamble below is shared by every code cell in this notebook.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

plt.rcParams.update({
    "figure.figsize": (7.0, 4.0),
    "figure.dpi": 110,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "font.size": 11,
})
rng = np.random.default_rng(0)
np.set_printoptions(precision=4, suppress=True)

EPS = np.finfo(float).eps
print(f"machine epsilon = {EPS:.4e}")

machine epsilon = 2.2204e-16


## L0 — Concept Checks

### Problem L0.1 — An affine map is not linear

**Statement.** Decide whether $T : \mathbb{R}^2 \to \mathbb{R}^2$, $T(x, y) = (x + 1,\; y)$, is
linear.

**Intuition.** Definition 3.1 forces $T(0) = 0$; a translation moves the origin.

**Solution.**

*Step 1.* $T(0, 0) = (1, 0) \neq (0, 0)$.

*Step 2.* Taking $c = 0$ in the homogeneity axiom gives $T(0) = 0$ for every linear map, so the
first step already decides it.

$$
\boxed{\text{No: } T(0) \neq 0, \text{ so } T \text{ is not linear.}}
$$

**Key takeaway.** Affine maps $x \mapsto Ax + b$ with $b \neq 0$ are not linear; Section 8.3 of
the theory notebook recovers them as linear maps one dimension up.

In [2]:
T_aff = lambda v: np.array([v[0] + 1.0, v[1]])
print("T(0,0)            =", T_aff(np.array([0.0, 0.0])))
u, v = np.array([1.0, 2.0]), np.array([3.0, -1.0])
print("T(u+v)            =", T_aff(u + v))
print("T(u) + T(v)       =", T_aff(u) + T_aff(v))
print("additivity gap    =", np.linalg.norm(T_aff(u + v) - T_aff(u) - T_aff(v)))
assert np.linalg.norm(T_aff(np.zeros(2))) > 0.5

T(0,0)            = [1. 0.]
T(u+v)            = [5. 1.]
T(u) + T(v)       = [6. 1.]
additivity gap    = 1.0


### Problem L0.2 — The matrix of the identity

**Statement.** Give $[\operatorname{id}]_E$ for $\operatorname{id} : \mathbb{R}^n \to \mathbb{R}^n$
in the standard basis.

**Intuition.** Definition 3.4 says the columns are the images of the basis vectors, and the
identity fixes each one.

**Solution.**

*Step 1.* $\operatorname{id}(e_j) = e_j$, so column $j$ is $e_j$.

$$
\boxed{[\operatorname{id}]_E = I_n}
$$

**Key takeaway.** The identity has matrix $I$ only when the same basis is used on both sides;
with two different bases its matrix is the change-of-basis matrix $P$ of Definition 3.7.

In [3]:
n = 4
Bstd = np.eye(n)
Bother = np.array([[1.0, 1, 0, 0], [0, 1, 1, 0], [0, 0, 1, 1], [1, 0, 0, 1]])
print("[id]_{E,E} =\n", np.linalg.solve(Bstd, Bstd))
print("[id]_{E,B'} = columns of B' =\n", np.linalg.solve(Bstd, Bother))
assert np.allclose(np.linalg.solve(Bstd, Bstd), np.eye(n))

[id]_{E,E} =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[id]_{E,B'} = columns of B' =
 [[1. 1. 0. 0.]
 [0. 1. 1. 0.]
 [0. 0. 1. 1.]
 [1. 0. 0. 1.]]


### Problem L0.3 — A matrix from the images of the basis vectors

**Statement.** A linear $T : \mathbb{R}^2 \to \mathbb{R}^3$ satisfies $T(e_1) = (2, 3, -1)$ and
$T(e_2) = (0, -4, 5)$. Write its standard matrix.

**Intuition.** Definition 3.4 again: the columns *are* the images.

**Solution.**

*Step 1.* Stack the two images as columns.

$$
\boxed{A = \begin{pmatrix} 2 & 0 \\ 3 & -4 \\ -1 & 5 \end{pmatrix}}
$$

**Key takeaway.** Theorem 4.1(i) says these two vectors may be chosen freely and determine $T$
on all of $\mathbb{R}^2$.

In [4]:
A03 = np.column_stack([[2.0, 3.0, -1.0], [0.0, -4.0, 5.0]])
print("A =\n", A03)
print("A e1 =", A03 @ np.array([1.0, 0.0]), "   A e2 =", A03 @ np.array([0.0, 1.0]))
print("A (2,-3) =", A03 @ np.array([2.0, -3.0]), " = 2 T(e1) - 3 T(e2)")
assert np.allclose(A03 @ np.array([2.0, -3.0]),
                   2 * np.array([2.0, 3.0, -1.0]) - 3 * np.array([0.0, -4.0, 5.0]))

A =
 [[ 2.  0.]
 [ 3. -4.]
 [-1.  5.]]
A e1 = [ 2.  3. -1.]    A e2 = [ 0. -4.  5.]
A (2,-3) = [  4.  18. -17.]  = 2 T(e1) - 3 T(e2)


### Problem L0.4 — The Euclidean norm is not linear

**Statement.** Decide whether $T : \mathbb{R}^2 \to \mathbb{R}$, $T(x, y) = \sqrt{x^2 + y^2}$, is
linear.

**Intuition.** A norm is never negative, so it cannot follow a negative scalar.

**Solution.**

*Step 1.* $T(-1, 0) = 1$ while $(-1)\,T(1, 0) = -1$.

$$
\boxed{\text{No: homogeneity fails at } c = -1 .}
$$

**Key takeaway.** $T(0) = 0$ is necessary and nowhere near sufficient; the norm satisfies it and
is still not linear.

In [5]:
nrm = lambda v: float(np.linalg.norm(v))
w = np.array([1.0, 0.0])
print("T(0)        =", nrm(np.zeros(2)), " (necessary condition holds)")
print("T(-1 * w)   =", nrm(-w), "   -1 * T(w) =", -nrm(w))
print("gap         =", abs(nrm(-w) + nrm(w)))
assert abs(nrm(-w) - (-nrm(w))) > 1.0

T(0)        = 0.0  (necessary condition holds)
T(-1 * w)   = 1.0    -1 * T(w) = -1.0
gap         = 2.0


### Problem L0.5 — A shear from its action on the basis

**Statement.** Find the standard matrix of the map fixing $(1, 0)$ and sending $(0, 1)$ to
$(3, 1)$.

**Intuition.** Two images, two columns.

**Solution.**

*Step 1.* Column $1$ is $(1, 0)^{\top}$ and column $2$ is $(3, 1)^{\top}$.

$$
\boxed{A = \begin{pmatrix} 1 & 3 \\ 0 & 1 \end{pmatrix}}
$$

**Key takeaway.** A shear leaves the area of every region unchanged, as the Section 2 figure of
the theory notebook shows.

In [6]:
A05 = np.array([[1.0, 3.0], [0.0, 1.0]])
sq = np.array([[0.0, 1.0, 1.0, 0.0], [0.0, 0.0, 1.0, 1.0]])
img = A05 @ sq
area = 0.5 * abs(np.sum(img[0] * np.roll(img[1], -1) - np.roll(img[0], -1) * img[1]))
print("A =\n", A05, "\narea of the sheared unit square =", area)
assert np.allclose(A05 @ np.array([0.0, 1.0]), [3.0, 1.0])
assert np.isclose(area, 1.0)

A =
 [[1. 3.]
 [0. 1.]] 
area of the sheared unit square = 1.0


### Problem L0.6 — Change of basis into the standard basis

**Statement.** Give the matrix converting $B$-coordinates into standard coordinates, for
$B = \bigl( (1,2), (3,4) \bigr)$.

**Intuition.** Definition 3.7: the columns are the new basis vectors written in the old one, and
here the old basis is standard.

**Solution.**

*Step 1.* $[(1,2)]_E = (1,2)^{\top}$ and $[(3,4)]_E = (3,4)^{\top}$.

$$
\boxed{P = [\operatorname{id}]_{E,B} = \begin{pmatrix} 1 & 3 \\ 2 & 4 \end{pmatrix}}
$$

**Key takeaway.** Going the other way costs an inverse: $[x]_B = P^{-1}[x]_E$.

In [7]:
P06 = np.array([[1.0, 3.0], [2.0, 4.0]])
x_std = np.array([5.0, 8.0])
x_B = np.linalg.solve(P06, x_std)
print("P =\n", P06, "\n[x]_B =", x_B, "   P [x]_B =", P06 @ x_B, "   x =", x_std)
assert np.allclose(P06 @ x_B, x_std)

P =
 [[1. 3.]
 [2. 4.]] 
[x]_B = [2. 1.]    P [x]_B = [5. 8.]    x = [5. 8.]


### Problem L0.7 — Additive but not homogeneous

**Statement.** Let $T : \mathbb{C} \to \mathbb{C}$, $T(z) = \bar{z}$, with $\mathbb{C}$ regarded
as a one-dimensional vector space **over $\mathbb{C}$**. Is $T$ linear?

**Intuition.** Conjugation respects sums exactly, and reverses the imaginary part of a scalar.

**Solution.**

*Step 1.* $\overline{z + w} = \bar{z} + \bar{w}$, so $T$ is additive.

*Step 2.* $T(iz) = \overline{iz} = -i\bar{z}$, while $i\,T(z) = i\bar{z}$. These differ whenever
$z \neq 0$.

$$
\boxed{\text{No over } \mathbb{C}\text{: additive but not homogeneous. Yes over } \mathbb{R} .}
$$

**Key takeaway.** The two axioms of Definition 3.1 are independent, and the field is part of the
question: the same function is $\mathbb{R}$-linear with matrix $\operatorname{diag}(1, -1)$.

In [8]:
z, w, c = 3 + 4j, -1 + 2j, 1j
print("additivity gap  =", abs(np.conj(z + w) - np.conj(z) - np.conj(w)))
print("T(cz) =", np.conj(c * z), "   c T(z) =", c * np.conj(z))
print("homogeneity gap =", abs(np.conj(c * z) - c * np.conj(z)))
R_conj = np.diag([1.0, -1.0])
xy = np.array([z.real, z.imag])
print("as a real map: R (x,y) =", R_conj @ xy, "  matches (Re z, -Im z) =",
      np.array([np.conj(z).real, np.conj(z).imag]))
assert abs(np.conj(z + w) - np.conj(z) - np.conj(w)) < 1e-15
assert abs(np.conj(c * z) - c * np.conj(z)) > 1.0
assert np.allclose(R_conj @ xy, [np.conj(z).real, np.conj(z).imag])

additivity gap  = 0.0
T(cz) = (-4-3j)    c T(z) = (4+3j)
homogeneity gap = 10.0
as a real map: R (x,y) = [ 3. -4.]   matches (Re z, -Im z) = [ 3. -4.]


## L1 — Foundations

### Problem L1.1 — Reflection across the $x$-axis

**Statement.** Show that $T(x, y) = (x, -y)$ satisfies both axioms of Definition 3.1 and find its
standard matrix.

**Intuition.** Reflection acts coordinatewise by fixed scalars, and scalars commute with sums.

**Solution.**

*Step 1 — additivity.* For $u = (x_1, y_1)$ and $v = (x_2, y_2)$,

$$
T(u + v) = \bigl( x_1 + x_2,\; -(y_1 + y_2) \bigr) = (x_1, -y_1) + (x_2, -y_2) = T(u) + T(v) .
$$

*Step 2 — homogeneity.* $T(cu) = (cx_1, -cy_1) = c\,(x_1, -y_1) = c\,T(u)$.

*Step 3 — the matrix.* $T(e_1) = (1, 0)$ and $T(e_2) = (0, -1)$.

$$
\boxed{A = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}}
$$

**Key takeaway.** Every map defined coordinatewise by fixed scalar multiples is linear and
diagonal; reflections across lines through the origin are the diagonal case in a rotated basis.

In [9]:
A11 = np.diag([1.0, -1.0])
u1, v1, c1 = np.array([2.0, -3.0]), np.array([-1.0, 5.0]), 2.5
print("additivity residual  =", np.linalg.norm(A11 @ (u1 + v1) - (A11 @ u1 + A11 @ v1)))
print("homogeneity residual =", np.linalg.norm(A11 @ (c1 * u1) - c1 * (A11 @ u1)))
print("A A^T =\n", A11 @ A11.T, " (orthogonal, so lengths are preserved)")
assert np.allclose(A11 @ A11.T, np.eye(2))

additivity residual  = 0.0
homogeneity residual = 0.0
A A^T =
 [[1. 0.]
 [0. 1.]]  (orthogonal, so lengths are preserved)


### Problem L1.2 — A basis for the kernel

**Statement.** Find a basis of $\ker T$ for $T : \mathbb{R}^3 \to \mathbb{R}^2$,
$T(x, y, z) = (x + y,\; y + z)$.

**Intuition.** The kernel is the solution set of a homogeneous system.

**Solution.**

*Step 1.* $x + y = 0$ and $y + z = 0$ give $x = -y$ and $z = -y$.

*Step 2.* Putting $y = -t$ gives $(x, y, z) = t\,(1, -1, 1)$.

$$
\boxed{\ker T = \operatorname{span} \lbrace (1, -1, 1)^{\top} \rbrace, \qquad \operatorname{nullity}(T) = 1}
$$

**Key takeaway.** Rank-nullity then forces $\operatorname{rank}(T) = 3 - 1 = 2$, so $T$ is onto
$\mathbb{R}^2$ without any further computation.

In [10]:
T12 = np.array([[1.0, 1.0, 0.0], [0.0, 1.0, 1.0]])
k12 = np.array([1.0, -1.0, 1.0])
print("T k =", T12 @ k12, "   rank =", np.linalg.matrix_rank(T12),
      "   nullity =", 3 - np.linalg.matrix_rank(T12))
assert np.allclose(T12 @ k12, 0.0)
assert np.linalg.matrix_rank(T12) == 2

T k = [0. 0.]    rank = 2    nullity = 1


### Problem L1.3 — A basis for the image

**Statement.** Find a basis of $\operatorname{im} T$ for the map with matrix

$$
A = \begin{pmatrix} 1 & 2 & 3 \\ 2 & 4 & 6 \\ 0 & 1 & 1 \end{pmatrix}.
$$

**Intuition.** The image is the column space, so discard columns that repeat information.

**Solution.**

*Step 1.* The columns are $a_1 = (1,2,0)$, $a_2 = (2,4,1)$, $a_3 = (3,6,1)$, and
$a_3 = a_1 + a_2$.

*Step 2.* $a_1$ and $a_2$ are not multiples of each other, so they are independent.

$$
\boxed{\operatorname{im} T = \operatorname{span}\lbrace (1,2,0)^{\top}, (2,4,1)^{\top} \rbrace, \qquad \operatorname{rank}(T) = 2}
$$

**Key takeaway.** A basis of the image is always available as a subset of the columns, which is
exactly the matrix $C$ of the rank factorization in Theorem 4.7.

In [11]:
A13 = np.array([[1.0, 2.0, 3.0], [2.0, 4.0, 6.0], [0.0, 1.0, 1.0]])
print("a1 + a2 - a3 =", A13[:, 0] + A13[:, 1] - A13[:, 2])
print("rank(A) =", np.linalg.matrix_rank(A13),
      "   rank of the first two columns =", np.linalg.matrix_rank(A13[:, :2]))
assert np.allclose(A13[:, 0] + A13[:, 1], A13[:, 2])
assert np.linalg.matrix_rank(A13) == 2

a1 + a2 - a3 = [0. 0. 0.]
rank(A) = 2    rank of the first two columns = 2


### Problem L1.4 — Rank-nullity on a $3 \times 4$ matrix

**Statement.** Verify Theorem 4.3 for

$$
A = \begin{pmatrix} 1 & 0 & 2 & 1 \\ 0 & 1 & -1 & 2 \\ 1 & 1 & 1 & 3 \end{pmatrix}.
$$

**Intuition.** Reduce, count pivots, count free variables, and check that the two counts add to
the number of columns.

**Solution.**

*Step 1 — reduce.* $R_3 \leftarrow R_3 - R_1 - R_2$ annihilates the last row, leaving

$$
\begin{pmatrix} 1 & 0 & 2 & 1 \\ 0 & 1 & -1 & 2 \\ 0 & 0 & 0 & 0 \end{pmatrix},
$$

so there are two pivots and $\operatorname{rank}(A) = 2$.

*Step 2 — free variables.* $x_3$ and $x_4$ are free, with $x_1 = -2x_3 - x_4$ and
$x_2 = x_3 - 2x_4$, giving nullity $2$.

$$
\boxed{\operatorname{rank}(A) + \operatorname{nullity}(A) = 2 + 2 = 4 = \dim \mathbb{R}^4}
$$

**Key takeaway.** The count is forced: once two of the four input directions are destroyed, only
two can survive in the image.

In [12]:
A14 = np.array([[1.0, 0.0, 2.0, 1.0], [0.0, 1.0, -1.0, 2.0], [1.0, 1.0, 1.0, 3.0]])
N14 = np.column_stack([[-2.0, 1.0, 1.0, 0.0], [-1.0, -2.0, 0.0, 1.0]])
r14 = np.linalg.matrix_rank(A14)
print("rank =", r14, "  nullity =", N14.shape[1], "  sum =", r14 + N14.shape[1])
print("A @ null basis =\n", A14 @ N14)
print("row3 - row1 - row2 =", A14[2] - A14[0] - A14[1])
assert r14 == 2 and np.allclose(A14 @ N14, 0.0)
assert r14 + N14.shape[1] == 4

rank = 2   nullity = 2   sum = 4
A @ null basis =
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
row3 - row1 - row2 = [0. 0. 0. 0.]


### Problem L1.5 — An operator in a non-standard basis

**Statement.** For $T(x, y) = (3x - y,\; x + y)$ and $B = \bigl( (1, 2), (1, -1) \bigr)$, compute
$[T]_B$.

**Intuition.** Apply $T$ to each basis vector, then re-express the answer in the same basis.

**Solution.**

*Step 1 — images.* $T(1, 2) = (1, 3)$ and $T(1, -1) = (4, 0)$.

*Step 2 — the coordinate rule.* Solving $c_1(1,2) + c_2(1,-1) = (a, b)$ gives

$$
c_1 = \frac{a + b}{3}, \qquad c_2 = \frac{2a - b}{3} .
$$

*Step 3 — the two columns.* $(1,3) \mapsto \bigl( \tfrac43, -\tfrac13 \bigr)$ and
$(4,0) \mapsto \bigl( \tfrac43, \tfrac83 \bigr)$.

$$
\boxed{[T]_B = \begin{pmatrix} \tfrac{4}{3} & \tfrac{4}{3} \\[2pt] -\tfrac{1}{3} & \tfrac{8}{3} \end{pmatrix}}
$$

**Key takeaway.** The trace is $4$ in both bases, as Theorem 4.6(iii) requires, even though no
entry is shared.

In [13]:
T15 = np.array([[3.0, -1.0], [1.0, 1.0]])
P15 = np.column_stack([[1.0, 2.0], [1.0, -1.0]])
T15_B = np.linalg.solve(P15, T15 @ P15)
print("[T]_B =\n", T15_B)
print("trace standard =", np.trace(T15), "   trace in B =", np.trace(T15_B))
assert np.allclose(T15_B, [[4 / 3, 4 / 3], [-1 / 3, 8 / 3]])
assert np.isclose(np.trace(T15), np.trace(T15_B))

[T]_B =
 [[ 1.3333  1.3333]
 [-0.3333  2.6667]]
trace standard = 4.0    trace in B = 4.0


### Problem L1.6 — Composing a rotation and a reflection

**Statement.** Let $T_1$ rotate by $90$ degrees counterclockwise and $T_2$ reflect across the
$y$-axis. Find the standard matrix of $T_2 \circ T_1$.

**Intuition.** Theorem 4.2: the matrix of a composite is the product, with the map applied first
on the right.

**Solution.**

*Step 1.* $A_1 = \begin{pmatrix} 0 & -1 \\ 1 & 0 \end{pmatrix}$ and
$A_2 = \begin{pmatrix} -1 & 0 \\ 0 & 1 \end{pmatrix}$.

*Step 2.* $A_2 A_1 = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$.

$$
\boxed{[T_2 \circ T_1]_E = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \text{ the reflection across } y = x .}
$$

**Key takeaway.** The other order gives the reflection across $y = -x$: composition is not
commutative, and the product records which map acts first.

In [14]:
A1_16 = np.array([[0.0, -1.0], [1.0, 0.0]])
A2_16 = np.array([[-1.0, 0.0], [0.0, 1.0]])
print("A2 A1 =\n", A2_16 @ A1_16, "\nA1 A2 =\n", A1_16 @ A2_16)
pt = np.array([2.0, 5.0])
print("(A2 A1) (2,5) =", A2_16 @ A1_16 @ pt, " which is (y, x)")
assert np.allclose(A2_16 @ A1_16, [[0.0, 1.0], [1.0, 0.0]])
assert not np.allclose(A2_16 @ A1_16, A1_16 @ A2_16)

A2 A1 =
 [[0. 1.]
 [1. 0.]] 
A1 A2 =
 [[ 0. -1.]
 [-1.  0.]]
(A2 A1) (2,5) = [5. 2.]  which is (y, x)


### Problem L1.7 — The derivative operator on $P_2$

**Statement.** For $D : P_2 \to P_2$, $D(p) = p'$, compute $[D]_B$ in the basis
$B = (1, x, x^2)$.

**Intuition.** Differentiate each basis polynomial and read off its coordinates.

**Solution.**

*Step 1.* $D(1) = 0$, $D(x) = 1$, $D(x^2) = 2x$.

*Step 2.* Their coordinate vectors are $(0,0,0)$, $(1,0,0)$ and $(0,2,0)$.

$$
\boxed{[D]_B = \begin{pmatrix} 0 & 1 & 0 \\ 0 & 0 & 2 \\ 0 & 0 & 0 \end{pmatrix}}
$$

**Key takeaway.** The matrix is strictly upper triangular, so $[D]_B^3 = 0$: differentiating a
quadratic three times gives zero, which is nilpotency read off the matrix.

In [15]:
D17 = np.array([[0.0, 1.0, 0.0], [0.0, 0.0, 2.0], [0.0, 0.0, 0.0]])
p17 = np.array([5.0, -3.0, 2.0])            # 5 - 3x + 2x^2
print("[D]_B =\n", D17)
print("D p    =", D17 @ p17, "  which is -3 + 4x")
print("D^3    =\n", np.linalg.matrix_power(D17, 3))
assert np.allclose(D17 @ p17, [-3.0, 4.0, 0.0])
assert np.allclose(np.linalg.matrix_power(D17, 3), 0.0)

[D]_B =
 [[0. 1. 0.]
 [0. 0. 2.]
 [0. 0. 0.]]
D p    = [-3.  4.  0.]   which is -3 + 4x
D^3    =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Problem L1.8 — Both bases non-standard, and the spaces different

**Statement.** Let $T : P_2 \to \mathbb{R}^2$ be $T(p) = \bigl( p(0), \int_0^1 p(x)\,dx \bigr)$.
Compute $[T]_{C,B}$ for

$$
B = \bigl( 1 + x,\; x + x^2,\; 1 + x^2 \bigr), \qquad C = \bigl( (2,1),\; (1,1) \bigr),
$$

and check the result on the constant polynomial $p = 1$.

**Intuition.** Nothing changes when both bases are exotic: evaluate $T$ on each vector of $B$ and
express the answer in $C$.

**Solution.**

*Step 1 — images.*

$$
T(1 + x) = \Bigl( 1, \tfrac{3}{2} \Bigr), \qquad
T(x + x^2) = \Bigl( 0, \tfrac{5}{6} \Bigr), \qquad
T(1 + x^2) = \Bigl( 1, \tfrac{4}{3} \Bigr) .
$$

*Step 2 — coordinates in $C$.* Solving $c_1(2,1) + c_2(1,1) = (a, b)$ gives $c_1 = a - b$ and
$c_2 = 2b - a$.

*Step 3 — the three columns.*

$$
\Bigl( -\tfrac12, 2 \Bigr), \qquad \Bigl( -\tfrac56, \tfrac53 \Bigr), \qquad \Bigl( -\tfrac13, \tfrac53 \Bigr) .
$$

$$
\boxed{[T]_{C,B} = \begin{pmatrix} -\tfrac{1}{2} & -\tfrac{5}{6} & -\tfrac{1}{3} \\[2pt] 2 & \tfrac{5}{3} & \tfrac{5}{3} \end{pmatrix}}
$$

*Step 4 — the check.* $1 = \tfrac12(1+x) - \tfrac12(x + x^2) + \tfrac12(1 + x^2)$, so
$[p]_B = \bigl( \tfrac12, -\tfrac12, \tfrac12 \bigr)$. Directly $T(1) = (1, 1)$, whose
$C$-coordinates are $(0, 1)$, and $[T]_{C,B}[p]_B = (0, 1)$ as well.

**Key takeaway.** Theorem 4.1(ii) is a statement about coordinates, not about $\mathbb{R}^n$:
neither space here is $\mathbb{R}^n$ with its standard basis and the identity still holds.

In [16]:
B18 = np.array([[1.0, 0.0, 1.0],       # coefficient columns of 1+x, x+x^2, 1+x^2
                [1.0, 1.0, 0.0],
                [0.0, 1.0, 1.0]])
C18 = np.column_stack([[2.0, 1.0], [1.0, 1.0]])


def T18(c):
    """p -> (p(0), integral of p over [0,1]) on coefficient vectors of P_2."""
    return np.array([c[0], c[0] + c[1] / 2.0 + c[2] / 3.0])


T18_CB = np.column_stack([np.linalg.solve(C18, T18(B18[:, j])) for j in range(3)])
p18 = np.array([1.0, 0.0, 0.0])
p18_B = np.linalg.solve(B18, p18)
print("[T]_{C,B} =\n", T18_CB)
print("[p]_B =", p18_B, "   [T(p)]_C =", np.linalg.solve(C18, T18(p18)),
      "   [T]_{C,B}[p]_B =", T18_CB @ p18_B)
assert np.allclose(T18_CB, [[-0.5, -5 / 6, -1 / 3], [2.0, 5 / 3, 5 / 3]])
assert np.allclose(p18_B, [0.5, -0.5, 0.5])
assert np.allclose(T18_CB @ p18_B, np.linalg.solve(C18, T18(p18)))

[T]_{C,B} =
 [[-0.5    -0.8333 -0.3333]
 [ 2.      1.6667  1.6667]]
[p]_B = [ 0.5 -0.5  0.5]    [T(p)]_C = [0. 1.]    [T]_{C,B}[p]_B = [0. 1.]


### Problem L1.9 — Invertibility and the inverse map

**Statement.** Decide whether $T(x, y, z) = (x + y,\; y + z,\; z + x)$ is invertible and, if so,
give $T^{-1}$.

**Intuition.** Theorem 4.5 turns invertibility into injectivity, and the system is small enough
to solve outright.

**Solution.**

*Step 1 — solve.* Set $u + v = x$, $v + w = y$, $w + u = z$. Adding all three gives
$u + v + w = \tfrac12 (x + y + z)$.

*Step 2 — subtract.* Subtracting each equation from that total,

$$
u = \tfrac12 (x - y + z), \qquad v = \tfrac12 (x + y - z), \qquad w = \tfrac12 (-x + y + z) .
$$

*Step 3 — conclude.* A solution exists for every right-hand side, so $T$ is surjective and
therefore invertible by Theorem 4.5.

$$
\boxed{T^{-1}(x, y, z) = \tfrac12 \bigl( x - y + z,\; x + y - z,\; -x + y + z \bigr)}
$$

**Key takeaway.** Solving the system once gives surjectivity, injectivity and the formula
together — the content of the dichotomy.

In [17]:
A19 = np.array([[1.0, 1.0, 0.0], [0.0, 1.0, 1.0], [1.0, 0.0, 1.0]])
Inv19 = 0.5 * np.array([[1.0, -1.0, 1.0], [1.0, 1.0, -1.0], [-1.0, 1.0, 1.0]])
print("A @ Inv =\n", A19 @ Inv19, "\nInv @ A =\n", Inv19 @ A19)
print("||A Inv - I||_F =", np.linalg.norm(A19 @ Inv19 - np.eye(3)))
assert np.allclose(A19 @ Inv19, np.eye(3))
assert np.allclose(Inv19, np.linalg.inv(A19))

A @ Inv =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
Inv @ A =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
||A Inv - I||_F = 0.0


### Problem L1.10 — Projection onto a line

**Statement.** Find the standard matrix of the orthogonal projection of $\mathbb{R}^2$ onto the
line $y = 2x$.

**Intuition.** Project onto the direction vector and rescale by its squared length.

**Solution.**

*Step 1.* A direction vector is $d = (1, 2)^{\top}$ with $d^{\top} d = 5$.

*Step 2.* The projection of $x$ is $\dfrac{d^{\top} x}{d^{\top} d}\, d$, which is the matrix
$\dfrac{d d^{\top}}{d^{\top} d}$ applied to $x$.

$$
\boxed{P = \frac{1}{5} \begin{pmatrix} 1 & 2 \\ 2 & 4 \end{pmatrix}}
$$

**Key takeaway.** $P^2 = P$ and $P^{\top} = P$: idempotent because projecting twice changes
nothing, symmetric because the projection is orthogonal. Problem L3.2 shows what an idempotent
without the symmetry looks like.

In [18]:
d110 = np.array([1.0, 2.0])
P110 = np.outer(d110, d110) / (d110 @ d110)
print("P =\n", P110)
print("||P^2 - P||_F =", np.linalg.norm(P110 @ P110 - P110),
      "   ||P - P^T||_F =", np.linalg.norm(P110 - P110.T))
print("rank =", np.linalg.matrix_rank(P110), "   trace =", np.trace(P110))
assert np.allclose(P110 @ P110, P110) and np.allclose(P110, P110.T)
assert np.isclose(np.trace(P110), 1.0)

P =


 [[0.2 0.4]
 [0.4 0.8]]
||P^2 - P||_F = 1.3877787807814457e-16    ||P - P^T||_F = 0.0
rank = 1    trace = 1.0


### Problem L1.11 — Transposition as an operator on $2 \times 2$ matrices

**Statement.** For $T(M) = M^{\top}$ on $\mathbb{R}^{2 \times 2}$, compute $[T]_B$ in the basis
$B = (E_{11}, E_{12}, E_{21}, E_{22})$.

**Intuition.** Transposition permutes the four basis matrices, swapping the two off-diagonal ones.

**Solution.**

*Step 1.* $T(E_{11}) = E_{11}$, $T(E_{12}) = E_{21}$, $T(E_{21}) = E_{12}$, $T(E_{22}) = E_{22}$.

*Step 2.* Reading those images as coordinate columns,

$$
\boxed{[T]_B = \begin{pmatrix} 1 & 0 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \end{pmatrix}}
$$

**Key takeaway.** $[T]_B^2 = I$, so transposition is an involution; its fixed space is the
symmetric matrices, of dimension $3$.

In [19]:
basis4 = [np.array([[1.0, 0], [0, 0]]), np.array([[0.0, 1], [0, 0]]),
          np.array([[0.0, 0], [1, 0]]), np.array([[0.0, 0], [0, 1]])]
vec = lambda M: M.reshape(-1)
T111 = np.column_stack([vec(E.T) for E in basis4])
print("[T]_B =\n", T111)
print("[T]_B^2 = I :", np.allclose(T111 @ T111, np.eye(4)))
print("dim of the fixed space =", 4 - np.linalg.matrix_rank(T111 - np.eye(4)))
assert np.allclose(T111, [[1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]])
assert 4 - np.linalg.matrix_rank(T111 - np.eye(4)) == 3

[T]_B =
 [[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
[T]_B^2 = I : True
dim of the fixed space = 3


### Problem L1.12 — The trace as a linear functional

**Statement.** Show that $f(M) = \operatorname{tr}(M)$ is linear on $\mathbb{R}^{n \times n}$ and
compute $\dim \ker f$.

**Intuition.** The trace is a sum of $n$ coordinates, and a coordinate sum is linear. Its image
is one-dimensional, so its kernel is a hyperplane.

**Solution.**

*Step 1 — linearity.*

$$
\operatorname{tr}(cM + N) = \sum_{i=1}^{n} (c\,m_{ii} + n_{ii}) = c \operatorname{tr}(M) + \operatorname{tr}(N) .
$$

*Step 2 — rank.* $f(I) = n \neq 0$, so $\operatorname{im} f = \mathbb{R}$ and
$\operatorname{rank}(f) = 1$.

*Step 3 — Theorem 4.3.* $\dim \mathbb{R}^{n \times n} = n^2$, so

$$
\boxed{\dim \ker f = n^2 - 1}
$$

**Key takeaway.** Every non-zero linear functional has a kernel of codimension exactly one: a
hyperplane through the origin.

In [20]:
for n112 in (2, 3, 4):
    f_row = np.eye(n112).reshape(1, -1)             # trace as a 1 x n^2 matrix
    print(f"n = {n112}: rank {np.linalg.matrix_rank(f_row)}, "
          f"nullity {n112 ** 2 - np.linalg.matrix_rank(f_row)}, n^2 - 1 = {n112 ** 2 - 1}")
    assert n112 ** 2 - np.linalg.matrix_rank(f_row) == n112 ** 2 - 1

n = 2: rank 1, nullity 3, n^2 - 1 = 3
n = 3: rank 1, nullity 8, n^2 - 1 = 8
n = 4: rank 1, nullity 15, n^2 - 1 = 15


### Problem L1.13 — Definite integration as a functional

**Statement.** For $J : P_2 \to \mathbb{R}$, $J(p) = \int_0^1 p(x)\,dx$, compute $[J]_{B}$ in the
basis $B = (1, x, x^2)$ of $P_2$ and the basis $(1)$ of $\mathbb{R}$.

**Intuition.** A functional has a one-row matrix, and its entries are the values on the basis.

**Solution.**

*Step 1.* $J(1) = 1$, $J(x) = \tfrac12$, $J(x^2) = \tfrac13$.

$$
\boxed{[J]_B = \begin{pmatrix} 1 & \tfrac{1}{2} & \tfrac{1}{3} \end{pmatrix}}
$$

**Key takeaway.** Integration against a fixed weight is a dot product with a fixed row, which is
why every quadrature rule is a linear functional.

In [21]:
J113 = np.array([[1.0, 0.5, 1 / 3]])
p113 = np.array([6.0, -6.0, 3.0])       # 6 - 6x + 3x^2
exact = 6.0 - 3.0 + 1.0                 # 6 - 6/2 + 3/3
print("[J]_B =", J113, "   [J]_B p =", (J113 @ p113).item(), "   exact integral =", exact)
assert np.isclose((J113 @ p113).item(), exact)

[J]_B = [[1.     0.5    0.3333]]    [J]_B p = 4.0    exact integral = 4.0


### Problem L1.14 — A similarity transformation

**Statement.** Let $A = \begin{pmatrix} 1 & 2 \\ 0 & 3 \end{pmatrix}$ and
$P = \begin{pmatrix} 1 & 1 \\ 1 & 2 \end{pmatrix}$. Compute $P^{-1} A P$ and check two
invariants.

**Intuition.** Theorem 4.6(ii): this is the same operator seen on the grid whose axes are the
columns of $P$.

**Solution.**

*Step 1.* $P^{-1} = \begin{pmatrix} 2 & -1 \\ -1 & 1 \end{pmatrix}$.

*Step 2.* $AP = \begin{pmatrix} 3 & 5 \\ 3 & 6 \end{pmatrix}$.

*Step 3.* $P^{-1}(AP) = \begin{pmatrix} 3 & 4 \\ 0 & 1 \end{pmatrix}$.

$$
\boxed{P^{-1} A P = \begin{pmatrix} 3 & 4 \\ 0 & 1 \end{pmatrix}}
$$

**Key takeaway.** Trace $4$ and rank $2$ on both sides, as Theorem 4.6(iii) guarantees, while
every entry has moved.

In [22]:
A114 = np.array([[1.0, 2.0], [0.0, 3.0]])
P114 = np.array([[1.0, 1.0], [1.0, 2.0]])
B114 = np.linalg.solve(P114, A114 @ P114)
print("P^-1 A P =\n", B114)
print("traces:", np.trace(A114), np.trace(B114),
      "   ranks:", np.linalg.matrix_rank(A114), np.linalg.matrix_rank(B114))
assert np.allclose(B114, [[3.0, 4.0], [0.0, 1.0]])
assert np.isclose(np.trace(A114), np.trace(B114))

P^-1 A P =
 [[3. 4.]
 [0. 1.]]
traces: 4.0 4.0    ranks: 2 2


### Problem L1.15 — Reflection across a plane

**Statement.** Find the standard matrix of the reflection of $\mathbb{R}^3$ across the plane
$x + y + z = 0$.

**Intuition.** Split a vector into a part along the normal and a part in the plane, then flip the
normal part.

**Solution.**

*Step 1.* The unit normal direction is $n = (1,1,1)^{\top}$ with $n^{\top} n = 3$.

*Step 2.* The component along $n$ is $\dfrac{n n^{\top}}{n^{\top} n} x$, and flipping it means
subtracting it twice:

$$
R = I - 2\,\frac{n n^{\top}}{n^{\top} n} .
$$

*Step 3.* Substituting,

$$
\boxed{R = \frac{1}{3} \begin{pmatrix} 1 & -2 & -2 \\ -2 & 1 & -2 \\ -2 & -2 & 1 \end{pmatrix}}
$$

**Key takeaway.** $R^{\top} R = I$ and $R^2 = I$: a reflection is orthogonal and is its own
inverse. Problem L3.10 characterizes exactly which matrices preserve the inner product.

In [23]:
n115 = np.ones(3)
R115 = np.eye(3) - 2 * np.outer(n115, n115) / (n115 @ n115)
print("R =\n", R115)
print("R n =", R115 @ n115, " (the normal is flipped)")
print("R (1,-1,0) =", R115 @ np.array([1.0, -1.0, 0.0]), " (a vector in the plane is fixed)")
print("||R^2 - I|| =", np.linalg.norm(R115 @ R115 - np.eye(3)),
      "   ||R^T R - I|| =", np.linalg.norm(R115.T @ R115 - np.eye(3)))
assert np.allclose(R115, np.array([[1.0, -2, -2], [-2, 1, -2], [-2, -2, 1]]) / 3)
assert np.allclose(R115 @ n115, -n115)
assert np.allclose(R115 @ R115, np.eye(3))

R =
 [[ 0.3333 -0.6667 -0.6667]
 [-0.6667  0.3333 -0.6667]
 [-0.6667 -0.6667  0.3333]]
R n = [-1. -1. -1.]  (the normal is flipped)
R (1,-1,0) = [ 1. -1.  0.]  (a vector in the plane is fixed)
||R^2 - I|| = 1.7667578002320924e-16    ||R^T R - I|| = 1.7667578002320924e-16


### Problem L1.16 — All invariant lines of an operator

**Statement.** Find every one-dimensional subspace of $\mathbb{R}^2$ mapped into itself by

$$
A = \begin{pmatrix} 2 & 1 \\ 0 & 3 \end{pmatrix}.
$$

**Intuition.** A line $\operatorname{span}(v)$ is invariant exactly when $Av$ is a multiple of
$v$, so solve that condition directly.

**Solution.**

*Step 1 — the condition.* $\operatorname{span}(v)$ with $v = (x, y) \neq 0$ is invariant if and
only if $Av = \lambda v$ for some scalar $\lambda$, that is

$$
(2x + y,\; 3y) = (\lambda x,\; \lambda y) .
$$

*Step 2 — case $y = 0$.* Then $x \neq 0$ and $Av = (2x, 0) = 2v$, so
$\operatorname{span}(1, 0)$ is invariant.

*Step 3 — case $y \neq 0$.* The second coordinate forces $\lambda = 3$, and the first then gives
$2x + y = 3x$, so $x = y$ and $v \propto (1, 1)$.

$$
\boxed{\operatorname{span}\lbrace (1,0)^{\top} \rbrace \text{ and } \operatorname{span}\lbrace (1,1)^{\top} \rbrace, \text{ and no others.}}
$$

**Key takeaway.** Invariant lines are found without any spectral theory; the scalars $2$ and $3$
that appear are the eigenvalues studied systematically in
[Module 06](../06_eigenvalues_eigenvectors_spectral_theory/first_principles.ipynb).

In [24]:
A116 = np.array([[2.0, 1.0], [0.0, 3.0]])
for v116, name in [(np.array([1.0, 0.0]), "(1,0)"), (np.array([1.0, 1.0]), "(1,1)"),
                   (np.array([1.0, 2.0]), "(1,2)")]:
    img = A116 @ v116
    parallel = abs(img[0] * v116[1] - img[1] * v116[0]) < 1e-12
    print(f"  A {name} = {img}   stays on the line: {parallel}")
assert abs((A116 @ np.array([1.0, 0.0]))[1]) < 1e-12
assert np.allclose(A116 @ np.array([1.0, 1.0]), 3 * np.array([1.0, 1.0]))
assert not np.allclose(A116 @ np.array([1.0, 2.0]),
                       (A116 @ np.array([1.0, 2.0]))[0] * np.array([1.0, 2.0]))

  A (1,0) = [2. 0.]   stays on the line: True


  A (1,1) = [3. 3.]   stays on the line: True
  A (1,2) = [4. 6.]   stays on the line: False


### Problem L1.17 — The dual basis

**Statement.** For $V = \mathbb{R}^2$ with $B = \bigl( v_1 = (1,1),\; v_2 = (1,-1) \bigr)$, find
the dual basis $B^{\star} = (f_1, f_2)$ of Definition 3.8.

**Intuition.** $f_i$ must read off the $i$-th coordinate in the basis $B$, so
$f_i(v_j) = \delta_{ij}$.

**Solution.**

*Step 1.* Write $f_1(x, y) = a x + b y$. The conditions $f_1(v_1) = 1$ and $f_1(v_2) = 0$ give
$a + b = 1$ and $a - b = 0$, so $a = b = \tfrac12$.

*Step 2.* For $f_2$, $a + b = 0$ and $a - b = 1$ give $a = \tfrac12$, $b = -\tfrac12$.

$$
\boxed{f_1(x,y) = \tfrac12 (x + y), \qquad f_2(x,y) = \tfrac12 (x - y)}
$$

**Key takeaway.** Stacking the $f_i$ as rows gives $P^{-1}$, where $P$ has the $v_j$ as columns:
the dual basis is the inverse of the basis, read one level up.

In [25]:
P117 = np.column_stack([[1.0, 1.0], [1.0, -1.0]])
dual = np.linalg.inv(P117)
print("rows of P^-1 =\n", dual)
print("f_i(v_j) matrix =\n", dual @ P117)
x117 = np.array([4.0, 2.0])
print("coordinates of (4,2) in B =", dual @ x117, "  check:",
      (dual @ x117)[0] * P117[:, 0] + (dual @ x117)[1] * P117[:, 1])
assert np.allclose(dual, [[0.5, 0.5], [0.5, -0.5]])
assert np.allclose(dual @ P117, np.eye(2))

rows of P^-1 =
 [[ 0.5  0.5]
 [ 0.5 -0.5]]
f_i(v_j) matrix =
 [[1. 0.]
 [0. 1.]]
coordinates of (4,2) in B = [3. 1.]   check: [4. 2.]


### Problem L1.18 — A product cannot gain rank

**Statement.** Prove $\operatorname{rank}(AB) \le \min \lbrace \operatorname{rank}(A), \operatorname{rank}(B) \rbrace$
directly from the definition of the column space, and exhibit non-zero $A$ and $B$ for which the
inequality is strict on both sides.

**Intuition.** Every output of $AB$ is an output of $A$, and it is also the image under $A$ of an
output of $B$.

**Solution.**

*Step 1 — bound by $\operatorname{rank}(A)$.* Every column of $AB$ is $A(Bx)$ for some $x$, so
$\operatorname{Col}(AB) \subseteq \operatorname{Col}(A)$ and the dimensions compare.

*Step 2 — bound by $\operatorname{rank}(B)$.* $\operatorname{Col}(AB) = A\bigl( \operatorname{Col}(B) \bigr)$,
the image of a subspace of dimension $\operatorname{rank}(B)$. By Theorem 4.3 applied to $A$
restricted to that subspace, its image has dimension at most $\operatorname{rank}(B)$.

*Step 3 — strictness.* Take

$$
A = \begin{pmatrix} 1 & 0 \\ 0 & 0 \end{pmatrix}, \qquad
B = \begin{pmatrix} 0 & 0 \\ 0 & 1 \end{pmatrix},
$$

both of rank $1$, with $AB = 0$ of rank $0$.

$$
\boxed{\operatorname{rank}(AB) \le \min \lbrace \operatorname{rank}(A), \operatorname{rank}(B) \rbrace, \text{ and the gap can be } 1 .}
$$

**Key takeaway.** Rank is destroyed by composition and never created, which is the ceiling on
what a low-rank adapter can express in Problem L2.4.

In [26]:
A118 = np.diag([1.0, 0.0])
B118 = np.diag([0.0, 1.0])
print("rank(A), rank(B), rank(AB) =", np.linalg.matrix_rank(A118),
      np.linalg.matrix_rank(B118), np.linalg.matrix_rank(A118 @ B118))
for _ in range(3):
    X = rng.standard_normal((5, 3))
    Y = rng.standard_normal((3, 6))
    rx, ry, rxy = (np.linalg.matrix_rank(X), np.linalg.matrix_rank(Y),
                   np.linalg.matrix_rank(X @ Y))
    print(f"  random: rank(X)={rx} rank(Y)={ry} rank(XY)={rxy} <= {min(rx, ry)}")
    assert rxy <= min(rx, ry)
assert np.linalg.matrix_rank(A118 @ B118) == 0

rank(A), rank(B), rank(AB) = 1 1 0
  random: rank(X)=3 rank(Y)=3 rank(XY)=3 <= 3
  random: rank(X)=3 rank(Y)=3 rank(XY)=3 <= 3
  random: rank(X)=3 rank(Y)=3 rank(XY)=3 <= 3


## L2 — Applications (AI/ML and Physics)

### Problem L2.1 — What a rank-deficient weight matrix destroys

**Statement.** A layer multiplies its input by
$W = \begin{pmatrix} 1 & 2 \\ 2 & 4 \end{pmatrix}$. How many input directions are mapped to
zero, and which ones?

**Intuition.** The lost directions are $\ker W$, and Theorem 4.3 counts them once the rank is
known.

**Solution.**

*Step 1 — rank.* The second column is twice the first, so $\operatorname{rank}(W) = 1$.

*Step 2 — Theorem 4.3.* $\dim \ker W = 2 - 1 = 1$.

*Step 3 — the direction.* $W(2, -1)^{\top} = (2 - 2,\; 4 - 4)^{\top} = 0$.

$$
\boxed{\dim \ker W = 1, \qquad \ker W = \operatorname{span}\lbrace (2, -1)^{\top} \rbrace}
$$

**Key takeaway.** No later layer can recover the lost coordinate: by Theorem 4.8 the rank of the
whole network is capped by the rank of this factor.

In [27]:
W21 = np.array([[1.0, 2.0], [2.0, 4.0]])
k21 = np.array([2.0, -1.0])
later = rng.standard_normal((3, 2))
print("rank(W) =", np.linalg.matrix_rank(W21), "  W (2,-1) =", W21 @ k21)
print("rank of a later layer composed with W:", np.linalg.matrix_rank(later @ W21),
      " <= rank(W) =", np.linalg.matrix_rank(W21))
assert np.allclose(W21 @ k21, 0.0)
assert np.linalg.matrix_rank(later @ W21) <= np.linalg.matrix_rank(W21)

rank(W) = 1   W (2,-1) = [0. 0.]
rank of a later layer composed with W: 1  <= rank(W) = 1


### Problem L2.2 — Homogeneous coordinates for an affine layer

**Statement.** Write the affine map $T(x) = Ax + b$ on $\mathbb{R}^2$, with
$A = \operatorname{diag}(2, 3)$ and $b = (1, -2)^{\top}$, as a single linear map on
$\mathbb{R}^3$.

**Intuition.** Append a constant coordinate $1$; the translation then becomes an extra column.

**Solution.**

*Step 1.* Embed $x \mapsto (x, 1)^{\top}$.

*Step 2.* The block matrix that reproduces $Ax + b$ and keeps the last coordinate at $1$ is

$$
M = \begin{pmatrix} A & b \\ 0^{\top} & 1 \end{pmatrix} .
$$

$$
\boxed{M = \begin{pmatrix} 2 & 0 & 1 \\ 0 & 3 & -2 \\ 0 & 0 & 1 \end{pmatrix}}
$$

**Key takeaway.** The embedded maps are closed under composition, so a stack of affine layers or
a chain of robot joints collapses into one matrix product by Theorem 4.2.

In [28]:
A22, b22 = np.diag([2.0, 3.0]), np.array([1.0, -2.0])
M22 = np.eye(3)
M22[:2, :2], M22[:2, 2] = A22, b22
x22 = np.array([1.5, -0.5])
print("M =\n", M22)
print("M (x,1) =", M22 @ np.append(x22, 1.0), "   A x + b =", A22 @ x22 + b22)
M22sq = M22 @ M22
print("M^2 =\n", M22sq, "\n  represents x -> A(Ax+b)+b =", A22 @ (A22 @ x22 + b22) + b22,
      " and M^2 gives", (M22sq @ np.append(x22, 1.0))[:2])
assert np.allclose((M22 @ np.append(x22, 1.0))[:2], A22 @ x22 + b22)
assert np.allclose((M22sq @ np.append(x22, 1.0))[:2], A22 @ (A22 @ x22 + b22) + b22)

M =


 [[ 2.  0.  1.]
 [ 0.  3. -2.]
 [ 0.  0.  1.]]
M (x,1) = [ 4.  -3.5  1. ]    A x + b = [ 4.  -3.5]
M^2 =
 [[ 4.  0.  3.]
 [ 0.  9. -8.]
 [ 0.  0.  1.]] 
  represents x -> A(Ax+b)+b = [  9.  -12.5]  and M^2 gives [  9.  -12.5]


### Problem L2.3 — A contractive layer has only the trivial fixed point

**Statement.** Let $A \in \mathbb{R}^{n \times n}$ with $\lVert A \rVert_{\mathrm{op}} = q \lt 1$.
Show that $Ax = x$ forces $x = 0$, that $\lVert A^k x_0 \rVert_2 \le q^k \lVert x_0 \rVert_2$, and
that $I - A$ is invertible.

**Intuition.** A strict contraction shrinks every vector, so nothing but the origin can survive
being mapped to itself.

**Solution.**

*Step 1 — the fixed point.* If $Ax = x$ then

$$
\lVert x \rVert_2 = \lVert Ax \rVert_2 \le q \lVert x \rVert_2,
\qquad \text{so} \qquad (1 - q)\lVert x \rVert_2 \le 0 .
$$

Since $1 - q \gt 0$, $\lVert x \rVert_2 = 0$.

*Step 2 — the decay.* Applying the defining inequality of Definition 3.9 $k$ times,
$\lVert A^k x_0 \rVert_2 \le q^k \lVert x_0 \rVert_2$.

*Step 3 — invertibility.* Step 1 says $\ker (I - A) = \lbrace 0 \rbrace$, so $I - A$ is injective
and therefore invertible by Theorem 4.5 — which is Step 1 of Proof 5.11.

$$
\boxed{x = 0 \text{ is the only fixed point, } \lVert A^k x_0 \rVert_2 \le q^k \lVert x_0 \rVert_2, \text{ and } (I - A)^{-1} \text{ exists.}}
$$

**Key takeaway.** A residual block $x \mapsto x + Ax$ with $\lVert A \rVert_{\mathrm{op}} \lt 1$
is invertible for the same reason, and the inverse is the Neumann series of Proposition 4.11.

In [29]:
Q23, _ = np.linalg.qr(rng.standard_normal((5, 5)))
A23 = 0.9 * Q23
q23 = np.linalg.norm(A23, 2)
x0 = rng.standard_normal(5)
print(f"||A||_op = {q23:.6f}")
xk = x0.copy()
for k in range(1, 6):
    xk = A23 @ xk
    print(f"  k={k}: ||A^k x0|| = {np.linalg.norm(xk):.6f}   bound q^k ||x0|| = "
          f"{q23 ** k * np.linalg.norm(x0):.6f}")
    assert np.linalg.norm(xk) <= q23 ** k * np.linalg.norm(x0) + 1e-12
fixed = np.linalg.solve(np.eye(5) - A23, np.zeros(5))
print("solution of (I - A) x = 0 :", fixed, "   ||(I-A)^-1||_op =",
      round(float(np.linalg.norm(np.linalg.inv(np.eye(5) - A23), 2)), 6))
assert np.allclose(fixed, 0.0)

||A||_op = 0.900000
  k=1: ||A^k x0|| = 1.568592   bound q^k ||x0|| = 1.568592
  k=2: ||A^k x0|| = 1.411733   bound q^k ||x0|| = 1.411733
  k=3: ||A^k x0|| = 1.270560   bound q^k ||x0|| = 1.270560
  k=4: ||A^k x0|| = 1.143504   bound q^k ||x0|| = 1.143504
  k=5: ||A^k x0|| = 1.029153   bound q^k ||x0|| = 1.029153
solution of (I - A) x = 0 : [0. 0. 0. 0. 0.]    ||(I-A)^-1||_op = 10.0


### Problem L2.4 — What a rank-$r$ adapter can represent

**Statement.** A LoRA update writes $\Delta W = BC$ with $B \in \mathbb{R}^{m \times r}$ and
$C \in \mathbb{R}^{r \times n}$. Show that the reachable set is exactly
$\lbrace \Delta : \operatorname{rank}(\Delta) \le r \rbrace$, count the parameters, and find when
the parameterization actually saves any.

**Intuition.** One direction is Theorem 4.8, the other is the rank factorization of Theorem 4.7.

**Solution.**

*Step 1 — the update is low rank.* $\operatorname{rank}(BC) \le \operatorname{rank}(B) \le r$ by
Theorem 4.8.

*Step 2 — every low-rank matrix is reachable.* If $\operatorname{rank}(\Delta) = s \le r$,
Theorem 4.7 gives $\Delta = C_0 R_0$ with $C_0 \in \mathbb{R}^{m \times s}$ and
$R_0 \in \mathbb{R}^{s \times n}$; pad both with zero columns and rows to width $r$.

*Step 3 — parameters.* $B$ and $C$ carry $r(m + n)$ entries against $mn$ for a dense update, so
the saving needs

$$
r(m + n) \lt mn \qquad \Longleftrightarrow \qquad r \lt \frac{mn}{m + n} .
$$

For $m = n = 4096$ the threshold is $r \lt 2048$.

$$
\boxed{\lbrace BC \rbrace = \lbrace \operatorname{rank} \le r \rbrace, \quad \text{cost } r(m+n), \quad \text{useful iff } r \lt \tfrac{mn}{m+n}}
$$

**Key takeaway.** The rank factorization is used here as a *parameterization*. Which rank-$r$
matrix best approximates a given target is a different question, settled by Eckart-Young in
[Module 07](../07_canonical_forms_and_svd/first_principles.ipynb).

In [30]:
m24, n24, r24 = 64, 48, 4
B24, C24 = rng.standard_normal((m24, r24)), rng.standard_normal((r24, n24))
dW24 = B24 @ C24
target = rng.standard_normal((m24, 3)) @ rng.standard_normal((3, n24))   # rank 3 <= r
Ct, Rt = target[:, :3], np.linalg.lstsq(target[:, :3], target, rcond=None)[0]
print("rank(BC) =", np.linalg.matrix_rank(dW24), " <= r =", r24)
print("rank-3 target reproduced by a padded factorization, residual =",
      round(float(np.linalg.norm(target - Ct @ Rt)), 12))
print(f"parameters: dense {m24 * n24}, LoRA {r24 * (m24 + n24)}, "
      f"threshold r < {m24 * n24 / (m24 + n24):.2f}")
print("for m = n = 4096 the threshold is r <", 4096 * 4096 / (4096 + 4096))
assert np.linalg.matrix_rank(dW24) == r24
assert np.linalg.norm(target - Ct @ Rt) < 1e-9
assert 4096 * 4096 / (4096 + 4096) == 2048

rank(BC) = 4  <= r = 4
rank-3 target reproduced by a padded factorization, residual = 0.0
parameters: dense 3072, LoRA 448, threshold r < 27.43
for m = n = 4096 the threshold is r < 2048.0


### Problem L2.5 — The Lipschitz constant of a layer

**Statement.** Let $f(x) = \sigma(Wx + b)$ with $\sigma$ applied entrywise and $1$-Lipschitz
(for example $\tanh$ or ReLU). Prove

$$
\lVert f(x) - f(y) \rVert_2 \le \lVert W \rVert_{\mathrm{op}} \lVert x - y \rVert_2
\le \lVert W \rVert_F \lVert x - y \rVert_2 ,
$$

and bound the constant of a stack of layers.

**Intuition.** The nonlinearity cannot amplify, so all the stretching is done by $W$; the
Frobenius norm is a cheap upper bound on the operator norm.

**Solution.**

*Step 1 — the nonlinearity.* Entrywise $1$-Lipschitzness gives
$\lVert \sigma(u) - \sigma(v) \rVert_2 \le \lVert u - v \rVert_2$, so
$\lVert f(x) - f(y) \rVert_2 \le \lVert W(x - y) \rVert_2$.

*Step 2 — the linear part.* Definition 3.9 gives
$\lVert W z \rVert_2 \le \lVert W \rVert_{\mathrm{op}} \lVert z \rVert_2$.

*Step 3 — the Frobenius bound.* Writing $w_i^{\top}$ for the rows of $W$ and applying
Cauchy-Schwarz to each,

$$
\lVert Wz \rVert_2^2 = \sum_i (w_i^{\top} z)^2 \le \Bigl( \sum_i \lVert w_i \rVert_2^2 \Bigr) \lVert z \rVert_2^2 = \lVert W \rVert_F^2 \lVert z \rVert_2^2 .
$$

*Step 4 — a stack.* Composing $L$ layers and using submultiplicativity,
$\operatorname{Lip}(f_L \circ \cdots \circ f_1) \le \prod_{l=1}^{L} \lVert W_l \rVert_{\mathrm{op}}$.

$$
\boxed{\operatorname{Lip}(f) \le \lVert W \rVert_{\mathrm{op}} \le \lVert W \rVert_F, \qquad \operatorname{Lip}(\text{stack}) \le \prod_l \lVert W_l \rVert_{\mathrm{op}}}
$$

**Key takeaway.** Spectral normalization divides $W$ by $\lVert W \rVert_{\mathrm{op}}$ precisely
to force this bound to $1$. The Frobenius bound is loose except for rank-one $W$, where
$W = uv^{\top}$ gives $\lVert W \rVert_{\mathrm{op}} = \lVert u \rVert_2 \lVert v \rVert_2 = \lVert W \rVert_F$.

In [31]:
W25 = rng.standard_normal((6, 5))
b25 = rng.standard_normal(6)
op25, fro25 = np.linalg.norm(W25, 2), np.linalg.norm(W25, "fro")
gaps = []
for _ in range(2000):
    dx = rng.standard_normal(5)
    dx /= np.linalg.norm(dx)
    x25 = rng.standard_normal(5)
    gaps.append(np.linalg.norm(np.tanh(W25 @ (x25 + dx) + b25) - np.tanh(W25 @ x25 + b25)))
print(f"largest measured stretch of the layer = {max(gaps):.6f}")
print(f"||W||_op = {op25:.6f}   ||W||_F = {fro25:.6f}")
u25, v25 = rng.standard_normal(6), rng.standard_normal(5)
W1 = np.outer(u25, v25)
print(f"rank one: ||W||_op = {np.linalg.norm(W1, 2):.6f}  ||W||_F = "
      f"{np.linalg.norm(W1, 'fro'):.6f}  ||u|| ||v|| = "
      f"{np.linalg.norm(u25) * np.linalg.norm(v25):.6f}")
assert max(gaps) <= op25 + 1e-9
assert op25 <= fro25 + 1e-12
assert np.isclose(np.linalg.norm(W1, 2), np.linalg.norm(W1, "fro"))

largest measured stretch of the layer = 2.804964
||W||_op = 4.624215   ||W||_F = 5.917939
rank one: ||W||_op = 2.595998  ||W||_F = 2.595998  ||u|| ||v|| = 2.595998


### Problem L2.6 — The Jacobian of a layer

**Statement.** For $f(x) = \sigma(Wx + b)$ with $\sigma$ smooth and applied entrywise, derive the
Jacobian $J_f(x)$.

**Intuition.** Each output depends on the inputs only through its own pre-activation, so the
chain rule attaches one scalar factor to each row of $W$.

**Solution.**

*Step 1.* Write $z = Wx + b$, so $z_i = \sum_j W_{ij} x_j + b_i$ and $f_i(x) = \sigma(z_i)$.

*Step 2.* By the chain rule,

$$
\frac{\partial f_i}{\partial x_j} = \sigma'(z_i)\, \frac{\partial z_i}{\partial x_j} = \sigma'(z_i)\, W_{ij} .
$$

*Step 3.* Scaling row $i$ by $\sigma'(z_i)$ is left multiplication by a diagonal matrix.

$$
\boxed{J_f(x) = \operatorname{diag}\bigl( \sigma'(Wx + b) \bigr)\, W}
$$

**Key takeaway.** The Jacobian is the linear map that best approximates $f$ near $x$; stacking
layers multiplies these matrices in reverse order, which is backpropagation and nothing else.

In [32]:
W26, b26 = rng.standard_normal((4, 3)), rng.standard_normal(4)
x26 = rng.standard_normal(3)
z26 = W26 @ x26 + b26
J26 = np.diag(1.0 - np.tanh(z26) ** 2) @ W26
h26 = 1e-6
J_num = np.column_stack([(np.tanh(W26 @ (x26 + h26 * np.eye(3)[:, j]) + b26)
                          - np.tanh(W26 @ (x26 - h26 * np.eye(3)[:, j]) + b26)) / (2 * h26)
                         for j in range(3)])
print("J analytic =\n", J26)
print("||J analytic - J finite difference||_F =", np.linalg.norm(J26 - J_num))
assert np.linalg.norm(J26 - J_num) < 1e-8

J analytic =
 [[ 0.034  -0.0641  0.1013]
 [ 0.077   0.0247 -0.0485]
 [ 0.5483 -0.5701 -0.325 ]
 [-0.2024  0.0179 -0.0243]]
||J analytic - J finite difference||_F = 6.586342226227729e-11


### Problem L2.7 — Composing Lorentz boosts (physics)

**Statement.** In units with $c = 1$, a boost of rapidity $\phi$ acts on $(t, x)$ by

$$
B(\phi) = \begin{pmatrix} \cosh \phi & -\sinh \phi \\ -\sinh \phi & \cosh \phi \end{pmatrix}.
$$

Show that $B(\phi_1) B(\phi_2) = B(\phi_1 + \phi_2)$, deduce the velocity-addition rule for
$\beta = \tanh \phi$, and verify that $B(\phi)$ preserves the interval
$t^2 - x^2$. Evaluate the combined speed for $\beta_1 = 0.6$ and $\beta_2 = 0.5$.

**Intuition.** Boosts are hyperbolic rotations, and rotations compose by adding angles.

**Solution.**

*Step 1 — the product.* Multiplying and using the addition formulas
$\cosh a \cosh b + \sinh a \sinh b = \cosh(a+b)$ and
$\sinh a \cosh b + \cosh a \sinh b = \sinh(a+b)$,

$$
B(\phi_1) B(\phi_2) = \begin{pmatrix} \cosh(\phi_1 + \phi_2) & -\sinh(\phi_1 + \phi_2) \\ -\sinh(\phi_1 + \phi_2) & \cosh(\phi_1 + \phi_2) \end{pmatrix} = B(\phi_1 + \phi_2) .
$$

*Step 2 — velocities.* With $\beta = \tanh \phi$, the hyperbolic tangent addition formula gives

$$
\beta = \tanh(\phi_1 + \phi_2) = \frac{\tanh \phi_1 + \tanh \phi_2}{1 + \tanh \phi_1 \tanh \phi_2} = \frac{\beta_1 + \beta_2}{1 + \beta_1 \beta_2} .
$$

*Step 3 — the interval.* With $\eta = \operatorname{diag}(1, -1)$, a direct computation gives
$B(\phi)^{\top} \eta\, B(\phi) = \eta$, so $t^2 - x^2$ is unchanged.

*Step 4 — the number.* $\beta = \dfrac{0.6 + 0.5}{1 + 0.30} = \dfrac{1.1}{1.3} = \dfrac{11}{13}$.

$$
\boxed{B(\phi_1)B(\phi_2) = B(\phi_1 + \phi_2), \qquad \beta = \frac{\beta_1 + \beta_2}{1 + \beta_1\beta_2} = \frac{11}{13} \approx 0.846154}
$$

**Key takeaway.** Rapidity is the coordinate in which boosts are a one-parameter group of linear
maps; the awkward velocity-addition rule is just $\tanh$ of a sum. No speed reaches $1$ because
$\tanh$ never does.

In [33]:
def boost(phi):
    return np.array([[np.cosh(phi), -np.sinh(phi)], [-np.sinh(phi), np.cosh(phi)]])


b1, b2 = 0.6, 0.5
phi1, phi2 = np.arctanh(b1), np.arctanh(b2)
prod = boost(phi1) @ boost(phi2)
eta = np.diag([1.0, -1.0])
beta_combined = np.tanh(phi1 + phi2)
print("B(phi1) B(phi2) =\n", prod, "\nB(phi1 + phi2) =\n", boost(phi1 + phi2))
print(f"difference = {np.abs(prod - boost(phi1 + phi2)).max():.3e}")
print(f"combined beta = {beta_combined:.12f}   (b1+b2)/(1+b1 b2) = {(b1 + b2) / (1 + b1 * b2):.12f}"
      f"   11/13 = {11 / 13:.12f}")
print("interval residual ||B^T eta B - eta||_F =",
      np.linalg.norm(boost(phi1).T @ eta @ boost(phi1) - eta))
assert np.allclose(prod, boost(phi1 + phi2))
assert np.isclose(beta_combined, 11 / 13)
assert np.allclose(boost(phi1).T @ eta @ boost(phi1), eta)

B(phi1) B(phi2) =
 [[ 1.8764 -1.5877]
 [-1.5877  1.8764]] 
B(phi1 + phi2) =
 [[ 1.8764 -1.5877]
 [-1.5877  1.8764]]
difference = 0.000e+00
combined beta = 0.846153846154   (b1+b2)/(1+b1 b2) = 0.846153846154   11/13 = 0.846153846154
interval residual ||B^T eta B - eta||_F = 0.0


### Problem L2.8 — The inertia tensor in a rotated frame (physics)

**Statement.** Two unit point masses sit at $r_{\pm} = \pm(1, 1, 0)$ about the centre of mass.
Compute the inertia tensor

$$
I = \sum_k m_k \bigl( \lVert r_k \rVert^2 I_3 - r_k r_k^{\top} \bigr),
$$

the angular momentum $L = I\omega$ for $\omega = (1, 0, 0)$, and the tensor in the frame rotated
by $45$ degrees about the $z$-axis.

**Intuition.** $I$ is a linear map from angular velocity to angular momentum, so changing frame
conjugates it exactly as Theorem 4.6 says.

**Solution.**

*Step 1 — one mass.* For $r = (1,1,0)$, $\lVert r \rVert^2 = 2$ and
$r r^{\top}$ has ones in the upper-left $2 \times 2$ block, giving
$\begin{pmatrix} 1 & -1 & 0 \\ -1 & 1 & 0 \\ 0 & 0 & 2 \end{pmatrix}$.

*Step 2 — both masses.* The second mass contributes the same matrix, so

$$
I = \begin{pmatrix} 2 & -2 & 0 \\ -2 & 2 & 0 \\ 0 & 0 & 4 \end{pmatrix}.
$$

*Step 3 — angular momentum.* $L = I(1,0,0)^{\top} = (2, -2, 0)^{\top}$, which is **not** parallel
to $\omega$.

*Step 4 — the rotated frame.* With $Q$ the rotation by $45$ degrees about $z$, Theorem 4.6 gives
$I' = Q^{-1} I Q = Q^{\top} I Q$, and the masses now lie along the first axis:

$$
I' = \operatorname{diag}(0, 4, 4) .
$$

$$
\boxed{I = \begin{pmatrix} 2 & -2 & 0 \\ -2 & 2 & 0 \\ 0 & 0 & 4 \end{pmatrix}, \quad L = (2, -2, 0)^{\top}, \quad I' = \operatorname{diag}(0, 4, 4)}
$$

**Key takeaway.** $L \parallel \omega$ only along a principal axis; the trace $8$ and the rank $2$
are frame-independent by Theorem 4.6(iii), and the rank is $2$ because spinning about the line
joining the masses moves nothing.

In [34]:
pos28 = np.array([[1.0, 1.0, 0.0], [-1.0, -1.0, 0.0]])
I28 = sum((r @ r) * np.eye(3) - np.outer(r, r) for r in pos28)
om28 = np.array([1.0, 0.0, 0.0])
c28 = np.cos(np.pi / 4)
Q28 = np.array([[c28, -c28, 0.0], [c28, c28, 0.0], [0.0, 0.0, 1.0]])
I28_rot = Q28.T @ I28 @ Q28
print("I =\n", I28, "\nL = I omega =", I28 @ om28)
print("I' =\n", np.round(I28_rot, 12))
print("trace:", np.trace(I28), np.trace(I28_rot), "   rank:",
      np.linalg.matrix_rank(I28), np.linalg.matrix_rank(I28_rot))
assert np.allclose(I28, [[2.0, -2, 0], [-2, 2, 0], [0, 0, 4]])
assert np.allclose(I28 @ om28, [2.0, -2.0, 0.0])
assert np.allclose(I28_rot, np.diag([0.0, 4.0, 4.0]), atol=1e-12)
assert np.isclose(np.trace(I28), np.trace(I28_rot))

I =


 [[ 2. -2.  0.]
 [-2.  2.  0.]
 [ 0.  0.  4.]] 
L = I omega = [ 2. -2.  0.]
I' =
 [[ 0.  0.  0.]
 [-0.  4.  0.]
 [ 0.  0.  4.]]
trace: 8.0 8.0    rank: 2 2


## L3 — Challenge Proofs

### Problem L3.1 — A cyclic vector for a nilpotent operator

**Statement.** Let $T : V \to V$ satisfy $T^3 = 0$ and $T^2 \neq 0$. Prove that some $v \in V$
makes $\lbrace v, Tv, T^2 v \rbrace$ linearly independent.

**Intuition.** Applying $T$ to a dependence relation kills the lowest-order term each time, so the
coefficients fall one by one.

**Solution.**

*Step 1 — choose $v$.* Since $T^2 \neq 0$ there is $v$ with $T^2 v \neq 0$.

*Step 2 — set up.* Suppose

$$
c_1 v + c_2 Tv + c_3 T^2 v = 0 . \tag{$\ast$}
$$

*Step 3 — apply $T^2$.* Using $T^3 = T^4 = 0$, only the first term survives:
$c_1 T^2 v = 0$, and $T^2v \neq 0$ gives $c_1 = 0$.

*Step 4 — apply $T$ to what is left.* From $c_2 Tv + c_3 T^2 v = 0$, applying $T$ gives
$c_2 T^2 v = 0$, so $c_2 = 0$.

*Step 5.* Finally $c_3 T^2 v = 0$ gives $c_3 = 0$.

$$
\boxed{\lbrace v, Tv, T^2v \rbrace \text{ is linearly independent, so } \dim V \ge 3 .}
$$

**Key takeaway.** A nilpotent operator with $T^{k} = 0 \ne T^{k-1}$ needs at least $k$ dimensions,
and the vectors $v, Tv, \dots, T^{k-1}v$ are the Jordan chain seen in
[Module 07](../07_canonical_forms_and_svd/first_principles.ipynb).

In [35]:
T31 = np.zeros((3, 3))                       # shift on R^3: e1 -> e2 -> e3 -> 0
T31[1, 0] = T31[2, 1] = 1.0
v31 = np.array([1.0, 0.0, 0.0])
chain = np.column_stack([v31, T31 @ v31, T31 @ T31 @ v31])
print("T^2 v =", T31 @ T31 @ v31, "   T^3 =\n", np.linalg.matrix_power(T31, 3))
print("rank of the chain =", np.linalg.matrix_rank(chain))
assert np.allclose(np.linalg.matrix_power(T31, 3), 0.0)
assert not np.allclose(np.linalg.matrix_power(T31, 2), 0.0)
assert np.linalg.matrix_rank(chain) == 3

T^2 v =

 [0. 0. 1.]    T^3 =
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
rank of the chain = 3


### Problem L3.2 — Idempotent operators split the space

**Statement.** Let $T : V \to V$ satisfy $T^2 = T$. Prove $V = \ker T \oplus \operatorname{im} T$,
and show by example that the two summands need not be orthogonal.

**Intuition.** Every vector splits into the part $T$ keeps and the part it discards, and those two
parts cannot overlap.

**Solution.**

*Step 1 — the sum.* For any $v$,

$$
v = (v - Tv) + Tv ,
$$

where $Tv \in \operatorname{im} T$ and $T(v - Tv) = Tv - T^2 v = 0$, so $v - Tv \in \ker T$.

*Step 2 — the intersection.* Let $x \in \ker T \cap \operatorname{im} T$. Then $x = Ty$ for some
$y$, and

$$
0 = Tx = T^2 y = Ty = x .
$$

*Step 3 — conclude.* The sum is all of $V$ and the intersection is trivial, so it is direct.

*Step 4 — an oblique example.* $T = \begin{pmatrix} 1 & 1 \\ 0 & 0 \end{pmatrix}$ satisfies
$T^2 = T$, with $\operatorname{im} T = \operatorname{span}(1,0)$ and
$\ker T = \operatorname{span}(1,-1)$: independent, spanning, and meeting at $45$ degrees.

$$
\boxed{V = \ker T \oplus \operatorname{im} T, \text{ a direct but in general oblique decomposition.}}
$$

**Key takeaway.** Orthogonality of the two summands is equivalent to $T = T^{\top}$, which is an
extra hypothesis; the projections of
[Module 04](../04_orthogonality_projections_and_qr/first_principles.ipynb) are the symmetric case.

In [36]:
T32 = np.array([[1.0, 1.0], [0.0, 0.0]])
im32 = np.array([1.0, 0.0])
ker32 = np.array([1.0, -1.0])
cosang = abs(im32 @ ker32) / (np.linalg.norm(im32) * np.linalg.norm(ker32))
print("||T^2 - T|| =", np.linalg.norm(T32 @ T32 - T32))
print("T (1,-1) =", T32 @ ker32, "   T (1,0) =", T32 @ im32)
print(f"angle between ker and im = {np.degrees(np.arccos(cosang)):.2f} degrees (not 90)")
print("T symmetric:", np.allclose(T32, T32.T))
v32 = np.array([3.0, 5.0])
print("v = (v - Tv) + Tv :", v32 - T32 @ v32, "+", T32 @ v32, "=", v32)
assert np.allclose(T32 @ T32, T32)
assert np.allclose((v32 - T32 @ v32) + T32 @ v32, v32)
assert not np.isclose(np.degrees(np.arccos(cosang)), 90.0)

||T^2 - T|| = 0.0
T (1,-1) = [0. 0.]    T (1,0) = [1. 0.]
angle between ker and im = 45.00 degrees (not 90)


T symmetric: False
v = (v - Tv) + Tv : [-5.  5.] + [8. 0.] = [3. 5.]


### Problem L3.3 — Trace and rank are similarity invariants

**Statement.** Let $A$ and $B$ represent the same operator $T : V \to V$ in two bases. Prove
$\operatorname{tr}(A) = \operatorname{tr}(B)$ and $\operatorname{rank}(A) = \operatorname{rank}(B)$.

**Intuition.** The two matrices differ by a conjugation, and both quantities are blind to it.

**Solution.**

*Step 1 — the relation.* By Theorem 4.6(ii) there is an invertible $P$ with $B = P^{-1} A P$.

*Step 2 — trace.* From the definition, for $X$ of size $n \times p$ and $Y$ of size $p \times n$,

$$
\operatorname{tr}(XY) = \sum_{i} \sum_{j} x_{ij} y_{ji} = \operatorname{tr}(YX) .
$$

Taking $X = P^{-1}$ and $Y = AP$,

$$
\operatorname{tr}(B) = \operatorname{tr}(P^{-1}(AP)) = \operatorname{tr}((AP)P^{-1}) = \operatorname{tr}(A) .
$$

*Step 3 — rank.* $\operatorname{Col}(AP) = \operatorname{Col}(A)$ because $P$ is onto, and left
multiplication by the invertible $P^{-1}$ is injective, so it preserves the dimension of a
subspace by Theorem 4.3. Hence $\operatorname{rank}(B) = \operatorname{rank}(A)$.

$$
\boxed{\operatorname{tr}(P^{-1}AP) = \operatorname{tr}(A), \qquad \operatorname{rank}(P^{-1}AP) = \operatorname{rank}(A)}
$$

**Key takeaway.** Only similarity invariants are properties of the operator. Two further ones,
the determinant and the characteristic polynomial, are built in
[Module 05](../05_determinants_trace_and_matrix_polynomials/first_principles.ipynb); nothing in
this module needs them.

In [37]:
A33 = rng.standard_normal((5, 5))
P33 = rng.standard_normal((5, 5))
B33 = np.linalg.solve(P33, A33 @ P33)
print(f"trace A = {np.trace(A33):.12f}   trace B = {np.trace(B33):.12f}")
print(f"|difference| = {abs(np.trace(A33) - np.trace(B33)):.3e}  = "
      f"{abs(np.trace(A33) - np.trace(B33)) / EPS:.1f} * eps")
print("ranks:", np.linalg.matrix_rank(A33), np.linalg.matrix_rank(B33))
X33, Y33 = rng.standard_normal((3, 7)), rng.standard_normal((7, 3))
print(f"tr(XY) - tr(YX) = {np.trace(X33 @ Y33) - np.trace(Y33 @ X33):.3e}")
assert abs(np.trace(A33) - np.trace(B33)) < 1e-10
assert np.linalg.matrix_rank(A33) == np.linalg.matrix_rank(B33)

trace A = -1.435710868150   trace B = -1.435710868150
|difference| = 4.441e-16  = 2.0 * eps
ranks: 5 5


tr(XY) - tr(YX) = 8.882e-16


### Problem L3.4 — No commutator equals the identity

**Statement.** Let $V$ be a non-zero finite-dimensional vector space over a field of
**characteristic zero**. Prove that no operators $S, T$ satisfy $ST - TS = I$. Then show the
hypothesis on the characteristic cannot be dropped.

**Intuition.** The trace of any commutator vanishes, while the trace of $I$ counts the dimension —
unless the field makes that count vanish too.

**Solution.**

*Step 1 — take traces.* Fix a basis and use $\operatorname{tr}(XY) = \operatorname{tr}(YX)$ from
Problem L3.3:

$$
\operatorname{tr}(ST - TS) = \operatorname{tr}(ST) - \operatorname{tr}(TS) = 0 .
$$

*Step 2 — compare.* If $ST - TS = I$ then $0 = \operatorname{tr}(I) = n \cdot 1$.

*Step 3 — conclude.* In characteristic zero $n \cdot 1 \neq 0$ for $n \ge 1$, a contradiction.

*Step 4 — the hypothesis is necessary.* Over $\mathbb{F}_2$ take $V = \mathbb{F}_2[x]/(x^2)$ with
basis $(1, x)$, let $T$ be multiplication by $x$ and $S$ the formal derivative:

$$
S = \begin{pmatrix} 0 & 1 \\ 0 & 0 \end{pmatrix}, \qquad
T = \begin{pmatrix} 0 & 0 \\ 1 & 0 \end{pmatrix},
\qquad
ST - TS = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix} = I \ \ \text{in } \mathbb{F}_2 ,
$$

because $-1 = 1$ there. Here $\operatorname{tr}(I) = 2 = 0$, so Step 2 produces no contradiction.

$$
\boxed{\text{Over a field of characteristic } 0, \; ST - TS \neq I \text{ in finite dimensions.}}
$$

**Key takeaway.** The canonical commutation relation $[X, P] = i\hbar I$ of quantum mechanics is
therefore impossible on a finite-dimensional complex space: position and momentum need an
infinite-dimensional Hilbert space.

In [38]:
S34 = np.array([[0, 1], [0, 0]], dtype=int)
T34 = np.array([[0, 0], [1, 0]], dtype=int)
comm = (S34 @ T34 - T34 @ S34) % 2
print("over F_2:  ST - TS mod 2 =\n", comm, "\n           I =\n", np.eye(2, dtype=int))
Sr, Tr = rng.standard_normal((4, 4)), rng.standard_normal((4, 4))
print(f"over R: trace of a commutator = {np.trace(Sr @ Tr - Tr @ Sr):.3e}"
      f"   trace of I_4 = {np.trace(np.eye(4))}")
assert np.array_equal(comm, np.eye(2, dtype=int))
assert abs(np.trace(Sr @ Tr - Tr @ Sr)) < 1e-10

over F_2:  ST - TS mod 2 =
 [[1 0]
 [0 1]] 
           I =
 [[1 0]
 [0 1]]
over R: trace of a commutator = 0.000e+00   trace of I_4 = 4.0


### Problem L3.5 — Sylvester's rank inequality, and what $AB = 0$ costs

**Statement.** For $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times p}$ prove

$$
\operatorname{rank}(A) + \operatorname{rank}(B) - n \le \operatorname{rank}(AB),
$$

then deduce that $AB = 0$ forces $\operatorname{rank}(A) + \operatorname{rank}(B) \le n$, and that
$A^2 = 0$ for a square $A$ forces $\operatorname{rank}(A) \le n/2$.

**Intuition.** The only rank $B$ can lose under $A$ is what falls inside $\ker A$, and that has
dimension $n - \operatorname{rank}(A)$.

**Solution.**

*Step 1 — restrict $A$.* Apply Theorem 4.3 to $x \mapsto Ax$ restricted to
$\operatorname{Col}(B)$:

$$
\operatorname{rank}(B) = \operatorname{rank}(AB) + \dim \bigl( \operatorname{Col}(B) \cap \operatorname{Null}(A) \bigr) .
$$

*Step 2 — bound the intersection.*
$\dim ( \operatorname{Col}(B) \cap \operatorname{Null}(A) ) \le \dim \operatorname{Null}(A) = n - \operatorname{rank}(A)$,
which rearranges to the claim. (This is Proof 5.8.)

*Step 3 — the corollary.* If $AB = 0$ then $\operatorname{rank}(AB) = 0$, so
$\operatorname{rank}(A) + \operatorname{rank}(B) \le n$.

*Step 4 — the square case.* Taking $B = A$ with $m = n = p$ gives
$2\operatorname{rank}(A) \le n$.

$$
\boxed{A^2 = 0 \implies \operatorname{rank}(A) \le \left\lfloor n/2 \right\rfloor}
$$

**Key takeaway.** A square-zero matrix must waste at least half its dimensions, and the bound is
attained by the block matrix $\begin{pmatrix} 0 & I \\ 0 & 0 \end{pmatrix}$.

In [39]:
for n35 in (4, 5, 6):
    k = n35 // 2
    N35 = np.zeros((n35, n35))
    N35[:k, n35 - k:] = np.eye(k)
    print(f"n = {n35}: ||N^2|| = {np.linalg.norm(N35 @ N35):.1e}, "
          f"rank = {np.linalg.matrix_rank(N35)}, bound = {n35 // 2}")
    assert np.allclose(N35 @ N35, 0.0)
    assert np.linalg.matrix_rank(N35) == n35 // 2
for _ in range(3):
    A35 = rng.standard_normal((6, 5)) @ np.diag([1.0, 1, 1, 1, 0])
    B35 = np.diag([1.0, 1, 1, 1, 0]) @ rng.standard_normal((5, 7))
    lo = np.linalg.matrix_rank(A35) + np.linalg.matrix_rank(B35) - 5
    print(f"  Sylvester: rank(A) + rank(B) - n = {lo} <= rank(AB) = "
          f"{np.linalg.matrix_rank(A35 @ B35)}")
    assert lo <= np.linalg.matrix_rank(A35 @ B35)

n = 4: ||N^2|| = 0.0e+00, rank = 2, bound = 2
n = 5: ||N^2|| = 0.0e+00, rank = 2, bound = 2
n = 6: ||N^2|| = 0.0e+00, rank = 3, bound = 3
  Sylvester: rank(A) + rank(B) - n = 3 <= rank(AB) = 4
  Sylvester: rank(A) + rank(B) - n = 3 <= rank(AB) = 4
  Sylvester: rank(A) + rank(B) - n = 3 <= rank(AB) = 4


### Problem L3.6 — Fitting's lemma

**Statement.** Let $T : V \to V$ with $\dim V = n \lt \infty$. Prove there is
$k \le n$ with $\ker(T^k) = \ker(T^{k+1})$ and
$V = \ker(T^k) \oplus \operatorname{im}(T^k)$.

**Intuition.** The kernels grow but cannot grow forever, and once they stop growing the space
splits into the part $T$ eventually kills and the part it permutes.

**Solution.**

*Step 1 — the chain stabilizes.* $\ker(T^j) \subseteq \ker(T^{j+1})$, so the dimensions form a
non-decreasing sequence bounded by $n$; it must stop increasing at some $k \le n$, giving
$\ker(T^k) = \ker(T^{k+1})$.

*Step 2 — it stays stopped.* If $\ker(T^{k}) = \ker(T^{k+1})$ and
$T^{k+2}v = 0$, then $T^{k+1}(Tv) = 0$, so $Tv \in \ker(T^{k+1}) = \ker(T^{k})$, hence
$T^{k+1}v = 0$ and $v \in \ker(T^{k+1}) = \ker(T^k)$. Induction gives
$\ker(T^{k+m}) = \ker(T^k)$ for all $m \ge 0$.

*Step 3 — trivial intersection.* Let $v \in \ker(T^k) \cap \operatorname{im}(T^k)$. Then
$v = T^k u$ and $T^k v = 0$, so $T^{2k} u = 0$, so $u \in \ker(T^{2k}) = \ker(T^k)$ by Step 2 and
$v = T^k u = 0$.

*Step 4 — dimensions.* Theorem 4.3 applied to $T^k$ gives
$\dim \ker(T^k) + \dim \operatorname{im}(T^k) = n$, so a trivial intersection forces the sum to be
all of $V$.

$$
\boxed{V = \ker(T^{k}) \oplus \operatorname{im}(T^{k}) \quad \text{for some } k \le n}
$$

**Key takeaway.** Every operator splits into a nilpotent part and an invertible part. That
splitting is the first step towards the Jordan form of
[Module 07](../07_canonical_forms_and_svd/first_principles.ipynb).

In [40]:
T36 = np.zeros((5, 5))
T36[0, 1] = T36[1, 2] = 1.0                  # nilpotent block of size 3
T36[3, 3], T36[3, 4], T36[4, 3] = 2.0, 1.0, 1.0   # invertible block of size 2
dims = [int(5 - np.linalg.matrix_rank(np.linalg.matrix_power(T36, j))) for j in range(1, 6)]
print("dim ker T^j for j = 1..5 :", dims)
k36 = next(j for j in range(1, 5) if dims[j] == dims[j - 1]) 
print("chain stabilizes at k =", k36)
Tk = np.linalg.matrix_power(T36, k36)
nk = 5 - np.linalg.matrix_rank(Tk)
print("dim ker T^k =", nk, "  dim im T^k =", np.linalg.matrix_rank(Tk), "  sum =", 5)
assert dims[-1] == dims[-2]
assert nk + np.linalg.matrix_rank(Tk) == 5

dim ker T^j for j = 1..5 :

 [1, 2, 3, 3, 3]
chain stabilizes at k = 3
dim ker T^k = 3   dim im T^k = 2   sum = 5


### Problem L3.7 — Commuting operators share an eigenvector

**Statement.** Let $S, T$ be operators on a non-zero finite-dimensional **complex** vector space
$V$ with $ST = TS$. Prove that some $w \neq 0$ satisfies $Sw = \lambda w$ and $Tw = \mu w$ for
scalars $\lambda, \mu$.

**Intuition.** Commuting means $T$ maps each eigenspace of $S$ into itself, so $T$ can be
restricted there and given an eigenvector of its own.

**Solution.**

*Step 1 — the existence lemma.* Every operator $R$ on a non-zero complex $V$ with $\dim V = d$ has
an eigenvalue. Pick $v \neq 0$; the $d + 1$ vectors $v, Rv, \dots, R^{d} v$ are dependent, so

$$
\sum_{j=0}^{d} a_j R^{j} v = 0
$$

with some $a_j \neq 0$. Let $t$ be the largest index with $a_t \neq 0$; $t \ge 1$, since $t = 0$
would give $a_0 v = 0$ with $v \neq 0$. Factor the polynomial over $\mathbb{C}$:

$$
a_t (R - \lambda_1 I) \cdots (R - \lambda_t I) v = 0 .
$$

Some factor must fail to be injective, so that $\lambda_i$ is an eigenvalue of $R$.

*Step 2 — an eigenspace of $S$.* By Step 1 pick an eigenvalue $\lambda$ of $S$ and set
$E_\lambda = \ker(S - \lambda I) \neq \lbrace 0 \rbrace$.

*Step 3 — $E_\lambda$ is $T$-invariant.* For $v \in E_\lambda$,

$$
S(Tv) = (ST)v = (TS)v = T(\lambda v) = \lambda (Tv),
$$

so $Tv \in E_\lambda$.

*Step 4 — restrict and repeat.* $T$ restricted to $E_\lambda$ is an operator on a non-zero
complex space, so by Step 1 it has an eigenvector $w \in E_\lambda$ with $Tw = \mu w$. Being in
$E_\lambda$, that same $w$ satisfies $Sw = \lambda w$.

$$
\boxed{\text{Commuting operators on a complex space share an eigenvector.}}
$$

**Key takeaway.** Iterating the argument simultaneously triangularizes any commuting family; the
stronger simultaneous *diagonalization* needs each operator to be diagonalizable and is proved in
[Module 06](../06_eigenvalues_eigenvectors_spectral_theory/first_principles.ipynb).

In [41]:
S37 = np.array([[2.0, 1.0], [0.0, 2.0]])
T37 = np.array([[3.0, 4.0], [0.0, 3.0]])
w37 = np.array([1.0, 0.0])
print("||ST - TS|| =", np.linalg.norm(S37 @ T37 - T37 @ S37))
print("S w =", S37 @ w37, " = 2 w      T w =", T37 @ w37, " = 3 w")
Srand = rng.standard_normal((4, 4))
Trand = Srand @ Srand - 2 * Srand + np.eye(4)
vals, vecs = np.linalg.eig(Srand)
resid = max(np.linalg.norm(Trand @ vecs[:, i]
                           - (vals[i] ** 2 - 2 * vals[i] + 1) * vecs[:, i]) for i in range(4))
print(f"random commuting pair: ||ST - TS|| = {np.linalg.norm(Srand @ Trand - Trand @ Srand):.3e},"
      f" shared-eigenvector residual = {resid:.3e}")
assert np.allclose(S37 @ T37, T37 @ S37)
assert np.allclose(S37 @ w37, 2 * w37) and np.allclose(T37 @ w37, 3 * w37)
assert resid < 1e-10

||ST - TS|| = 0.0
S w = [2. 0.]  = 2 w      T w = [3. 0.]  = 3 w
random commuting pair: ||ST - TS|| = 1.477e-15, shared-eigenvector residual = 6.771e-15


### Problem L3.8 — A resolution of the identity is orthogonal

**Statement.** Let $P_1, \dots, P_k$ be operators on $V$ with $P_i^2 = P_i$ and
$\sum_{i=1}^{k} P_i = I$. Prove $P_i P_j = 0$ whenever $i \neq j$.

**Intuition.** The ranks are forced to add up to $\dim V$, which makes the images independent, and
independence kills the cross terms.

**Solution.**

*Step 1 — trace equals rank for an idempotent.* By Problem L3.2,
$V = \ker P_i \oplus \operatorname{im} P_i$. In a basis adapted to that splitting $P_i$ has matrix
$\operatorname{diag}(I_{r_i}, 0)$, because $P_i u = u$ for $u \in \operatorname{im} P_i$. Trace is
a similarity invariant by Problem L3.3, so $\operatorname{tr}(P_i) = r_i = \operatorname{rank}(P_i)$.

*Step 2 — the ranks add to $n$.* Taking traces in $\sum_i P_i = I$,

$$
\sum_{i=1}^{k} r_i = \operatorname{tr}(I) = n .
$$

*Step 3 — the images are independent.* Every $v$ equals $\sum_i P_i v$, so
$V = \sum_i \operatorname{im} P_i$. Concatenating bases of the $\operatorname{im} P_i$ gives a
spanning list of exactly $n$ vectors, hence a basis, hence the sum is direct.

*Step 4 — kill the cross terms.* Fix $j$ and let $x \in \operatorname{im} P_j$, so $P_j x = x$.
Then $x = \sum_i P_i x$ is a decomposition of $x$ in the direct sum, and so is
$x = x + \sum_{i \neq j} 0$. Uniqueness gives $P_i x = 0$ for $i \neq j$. Applying this to
$x = P_j y$ for arbitrary $y$ gives $P_i P_j = 0$.

$$
\boxed{P_i P_j = 0 \quad \text{for all } i \neq j}
$$

**Key takeaway.** A partition of the identity into idempotents is automatically a decomposition of
$V$ into independent pieces; with symmetry added, this is the projector form
$A = \sum_i \lambda_i q_i q_i^{\top}$ of the spectral theorem.

In [42]:
V38 = np.array([[1.0, 1.0, 0.0], [0.0, 1.0, 1.0], [0.0, 0.0, 1.0]])
F38 = np.linalg.inv(V38)
Ps = [np.outer(V38[:, i], F38[i, :]) for i in range(3)]   # oblique, not symmetric
print("sum of P_i =\n", sum(Ps))
for i, Pi in enumerate(Ps):
    print(f"  P{i+1}: idempotent {np.allclose(Pi @ Pi, Pi)}, "
          f"trace {np.trace(Pi):.1f}, rank {np.linalg.matrix_rank(Pi)}")
for i in range(3):
    for j in range(3):
        if i != j:
            assert np.allclose(Ps[i] @ Ps[j], 0.0)
print("all cross products P_i P_j vanish for i != j")
assert np.allclose(sum(Ps), np.eye(3))
assert all(np.allclose(P @ P, P) for P in Ps)

sum of P_i =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
  P1: idempotent True, trace 1.0, rank 1
  P2: idempotent True, trace 1.0, rank 1
  P3: idempotent True, trace 1.0, rank 1
all cross products P_i P_j vanish for i != j


### Problem L3.9 — $I - AB$ and $I - BA$ stand or fall together

**Statement.** For $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times m}$, prove that
$I_m - AB$ is invertible if and only if $I_n - BA$ is, and give the inverse explicitly.

**Intuition.** Guess that the inverse differs from the identity by something sandwiched between
$B$ and $A$, then verify both products.

**Solution.**

*Step 1 — the candidate.* Assume $X = (I_m - AB)^{-1}$ exists and set

$$
Y = I_n + B X A .
$$

*Step 2 — one side.* Expanding and using $XABA$ carefully,

$$
(I_n - BA)Y = I_n + BXA - BA - BABXA = I_n - BA + B(I_m - AB)XA = I_n - BA + BA = I_n .
$$

*Step 3 — the other side.* Symmetrically,

$$
Y(I_n - BA) = I_n - BA + BXA - BXABA = I_n - BA + BX(I_m - AB)A = I_n .
$$

Both products are the identity, so $Y$ is a genuine two-sided inverse. (For square matrices a
one-sided inverse is automatically two-sided by Theorem 4.5, but here the two sides were checked
directly.)

*Step 4 — symmetry.* Swapping the roles of $A$ and $B$ gives the converse.

$$
\boxed{(I_n - BA)^{-1} = I_n + B(I_m - AB)^{-1} A}
$$

**Key takeaway.** This is the Woodbury identity in its simplest form, and it says that the
non-zero spectra of $AB$ and $BA$ agree — the content of Problem L3.11.

In [43]:
m39, n39 = 3, 5
A39 = 0.3 * rng.standard_normal((m39, n39))
B39 = 0.3 * rng.standard_normal((n39, m39))
X39 = np.linalg.inv(np.eye(m39) - A39 @ B39)
Y39 = np.eye(n39) + B39 @ X39 @ A39
print("||(I - BA) Y - I||_F =", np.linalg.norm((np.eye(n39) - B39 @ A39) @ Y39 - np.eye(n39)))
print("||Y (I - BA) - I||_F =", np.linalg.norm(Y39 @ (np.eye(n39) - B39 @ A39) - np.eye(n39)))
print("||Y - (I - BA)^-1||_F =", np.linalg.norm(Y39 - np.linalg.inv(np.eye(n39) - B39 @ A39)))
assert np.allclose((np.eye(n39) - B39 @ A39) @ Y39, np.eye(n39))
assert np.allclose(Y39 @ (np.eye(n39) - B39 @ A39), np.eye(n39))

||(I - BA) Y - I||_F = 2.3211486628577405e-16
||Y (I - BA) - I||_F = 2.410658300400146e-16
||Y - (I - BA)^-1||_F = 4.0279218242338813e-16


### Problem L3.10 — Preserving the inner product means orthogonal

**Statement.** Let $T : \mathbb{R}^n \to \mathbb{R}^n$ be linear with standard matrix $Q$. Prove

$$
\langle Tu, Tv \rangle = \langle u, v \rangle \text{ for all } u, v
\qquad \Longleftrightarrow \qquad
Q^{\top} Q = I .
$$

**Intuition.** Writing the inner product as $u^{\top}(Q^{\top}Q)v$ turns the condition into a
statement about one matrix, tested on basis vectors.

**Solution.**

*Step 1 — rewrite.* $\langle Tu, Tv \rangle = (Qu)^{\top}(Qv) = u^{\top}(Q^{\top}Q)v$.

*Step 2 — the condition.* Preservation says
$u^{\top}(Q^{\top}Q - I)v = 0$ for all $u, v$.

*Step 3 — test on the basis.* Taking $u = e_i$ and $v = e_j$ picks out the $(i,j)$ entry, so
every entry of $Q^{\top}Q - I$ is zero.

*Step 4 — converse.* If $Q^{\top}Q = I$ then Step 1 gives
$\langle Tu, Tv \rangle = u^{\top} v$ immediately.

$$
\boxed{T \text{ preserves the inner product} \iff Q^{\top} Q = I}
$$

**Key takeaway.** Lengths and angles are preserved together: taking $u = v$ shows that preserving
norms already forces orthogonality, by polarization.

In [44]:
ang310 = 0.7
Q310 = np.array([[np.cos(ang310), -np.sin(ang310)], [np.sin(ang310), np.cos(ang310)]])
u310, v310 = rng.standard_normal(2), rng.standard_normal(2)
print("||Q^T Q - I||_F =", np.linalg.norm(Q310.T @ Q310 - np.eye(2)))
print(f"<u,v> = {u310 @ v310:.10f}   <Qu,Qv> = {(Q310 @ u310) @ (Q310 @ v310):.10f}")
NotQ = np.array([[1.0, 1.0], [0.0, 1.0]])
print(f"for the shear: <u,v> = {u310 @ v310:.6f} but <Qu,Qv> = "
      f"{(NotQ @ u310) @ (NotQ @ v310):.6f}")
assert np.isclose(u310 @ v310, (Q310 @ u310) @ (Q310 @ v310))
assert not np.isclose(u310 @ v310, (NotQ @ u310) @ (NotQ @ v310))

||Q^T Q - I||_F = 2.9486149327106574e-17
<u,v> = 0.7544881064   <Qu,Qv> = 0.7544881064
for the shear: <u,v> = 0.754488 but <Qu,Qv> = 1.891101


### Problem L3.11 — $AB$ and $BA$ share their non-zero eigenvalues

**Statement.** Call $\lambda$ an eigenvalue of a square $M$ when $Mv = \lambda v$ for some
$v \neq 0$. Prove that for any $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times m}$,
every non-zero eigenvalue of $AB$ is an eigenvalue of $BA$, and conversely.

**Intuition.** Multiplying an eigenvector of $AB$ by $B$ produces a candidate eigenvector of
$BA$, and the only thing to check is that it is not zero.

**Solution.**

*Step 1 — transport the eigenvector.* Let $ABv = \lambda v$ with $v \neq 0$ and $\lambda \neq 0$.
Multiplying on the left by $B$,

$$
(BA)(Bv) = B(ABv) = \lambda (Bv) .
$$

*Step 2 — the candidate is non-zero.* If $Bv = 0$ then $ABv = 0 = \lambda v$, and $v \neq 0$
forces $\lambda = 0$, contrary to assumption.

*Step 3 — conclude and symmetrize.* So $Bv \neq 0$ is an eigenvector of $BA$ for $\lambda$.
Exchanging the roles of $A$ and $B$ gives the converse.

$$
\boxed{\lambda \neq 0 \text{ is an eigenvalue of } AB \iff \text{it is one of } BA .}
$$

**Key takeaway.** The eigenvalue $0$ genuinely differs: $AB$ and $BA$ have different sizes when
$m \neq n$, so the multiplicity of $0$ must absorb the difference.

In [45]:
A311, B311 = rng.standard_normal((3, 5)), rng.standard_normal((5, 3))
ev_ab = np.sort_complex(np.linalg.eigvals(A311 @ B311))
ev_ba = np.sort_complex(np.linalg.eigvals(B311 @ A311))
nz_ba = np.sort_complex(ev_ba[np.abs(ev_ba) > 1e-8])
print("eigenvalues of AB (3x3):", np.round(ev_ab, 6))
print("eigenvalues of BA (5x5):", np.round(ev_ba, 6))
print("non-zero eigenvalues of BA:", np.round(nz_ba, 6))
print("largest mismatch:", np.abs(np.sort_complex(ev_ab) - nz_ba).max())
assert np.abs(np.sort_complex(ev_ab) - nz_ba).max() < 1e-8

eigenvalues of AB (3x3): [-1.2959-3.5598j -1.2959+3.5598j -1.1342+0.j    ]
eigenvalues of BA (5x5): [-1.2959-3.5598j -1.2959+3.5598j -1.1342+0.j     -0.    +0.j
  0.    +0.j    ]
non-zero eigenvalues of BA: [-1.2959-3.5598j -1.2959+3.5598j -1.1342+0.j    ]


largest mismatch: 2.318213734067276e-15


### Problem L3.12 — The trace of a Kronecker product

**Statement.** For $A \in \mathbb{R}^{m \times m}$ and $B \in \mathbb{R}^{n \times n}$, prove
$\operatorname{tr}(A \otimes B) = \operatorname{tr}(A)\operatorname{tr}(B)$.

**Intuition.** The Kronecker product is a block matrix whose $i$-th diagonal block is $a_{ii}B$,
and the trace only sees diagonal blocks.

**Solution.**

*Step 1 — the block structure.* The $(i,j)$ block of $A \otimes B$ is $a_{ij}B$, so the diagonal
blocks are $a_{ii}B$ for $i = 1, \dots, m$.

*Step 2 — sum the diagonals.*

$$
\operatorname{tr}(A \otimes B) = \sum_{i=1}^{m} \operatorname{tr}(a_{ii} B) = \sum_{i=1}^{m} a_{ii} \operatorname{tr}(B) .
$$

*Step 3 — factor.*

$$
\operatorname{tr}(A \otimes B) = \Bigl( \sum_{i=1}^{m} a_{ii} \Bigr) \operatorname{tr}(B) = \operatorname{tr}(A)\operatorname{tr}(B) .
$$

$$
\boxed{\operatorname{tr}(A \otimes B) = \operatorname{tr}(A)\,\operatorname{tr}(B)}
$$

**Key takeaway.** $A \otimes B$ is the matrix of the induced map on the tensor product, so this
identity is the statement that the trace is multiplicative on independent subsystems — the
reason partition functions factor.

In [46]:
A312, B312 = rng.standard_normal((3, 3)), rng.standard_normal((4, 4))
K312 = np.kron(A312, B312)
print("shape of A kron B =", K312.shape)
print(f"tr(A kron B)   = {np.trace(K312):.12f}")
print(f"tr(A) tr(B)    = {np.trace(A312) * np.trace(B312):.12f}")
print(f"difference     = {abs(np.trace(K312) - np.trace(A312) * np.trace(B312)):.3e}")
print("rank(A kron B) =", np.linalg.matrix_rank(K312), " = rank(A) rank(B) =",
      np.linalg.matrix_rank(A312) * np.linalg.matrix_rank(B312))
assert abs(np.trace(K312) - np.trace(A312) * np.trace(B312)) < 1e-10

shape of A kron B =

 (12, 12)
tr(A kron B)   = 0.660534991505
tr(A) tr(B)    = 0.660534991505
difference     = 1.110e-16
rank(A kron B) = 12  = rank(A) rank(B) = 12


### Problem L3.13 — Factoring a map through a quotient

**Statement.** Let $T \in \mathcal{L}(V, W)$ and let $U \subseteq \ker T$ be a subspace, with
$\pi : V \to V/U$ the quotient map $\pi(v) = v + U$. Prove there is exactly one linear
$\widetilde{T} : V/U \to W$ with $\widetilde{T} \circ \pi = T$, show
$\ker \widetilde{T} = \ker T / U$, and deduce Theorem 4.4.

**Intuition.** Collapsing directions that $T$ already destroys cannot change what $T$ computes.

**Solution.**

*Step 1 — well defined.* Set $\widetilde{T}(v + U) = T(v)$. If $v + U = v' + U$ then
$v - v' \in U \subseteq \ker T$, so $T(v) = T(v')$ and the value does not depend on the
representative.

*Step 2 — linear.* $\widetilde{T}\bigl( (v + U) + c(u + U) \bigr) = T(v + cu) = T(v) + c\,T(u)$.

*Step 3 — unique.* Any $R$ with $R \circ \pi = T$ satisfies $R(v + U) = T(v)$, which is the
formula above; $\pi$ is surjective, so no freedom remains.

*Step 4 — the kernel.* $\widetilde{T}(v + U) = 0$ says $T(v) = 0$, that is $v \in \ker T$, so

$$
\ker \widetilde{T} = \lbrace v + U \mid v \in \ker T \rbrace = \ker T / U .
$$

*Step 5 — Theorem 4.4.* Take $U = \ker T$. Then $\ker \widetilde{T}$ is the zero coset alone, so
$\widetilde{T}$ is injective, and its image is $\operatorname{im} T$ because $\pi$ is onto.
Restricting the codomain gives an isomorphism.

$$
\boxed{V/\ker T \;\cong\; \operatorname{im} T, \qquad \text{and } \dim V = \dim \ker T + \operatorname{rank}(T) .}
$$

**Key takeaway.** Rank-nullity is the dimension count of this isomorphism, and the factorization
$T = \iota \circ \widetilde{T} \circ \pi$ is the universal property that makes quotients useful.

In [47]:
T313 = np.array([[1.0, 1.0, 0.0], [0.0, 1.0, 1.0]])
u313 = np.array([1.0, -1.0, 1.0])                    # spans ker T = U
reps = [rng.standard_normal(3) for _ in range(4)]
print("well-definedness: T is constant on cosets of U")
for v in reps:
    shift = rng.standard_normal()
    print(f"  ||T(v) - T(v + c u)|| = {np.linalg.norm(T313 @ v - T313 @ (v + shift * u313)):.3e}")
    assert np.linalg.norm(T313 @ v - T313 @ (v + shift * u313)) < 1e-12
print("dim V =", 3, "  dim ker T =", 3 - np.linalg.matrix_rank(T313),
      "  rank T =", np.linalg.matrix_rank(T313))
coset_basis = np.column_stack([np.array([1.0, 0.0, 0.0]), np.array([0.0, 0.0, 1.0])])
images = T313 @ coset_basis
print("images of two coset representatives =\n", images, "\n  independent:",
      np.linalg.matrix_rank(images) == 2)
assert np.linalg.matrix_rank(images) == 2
assert 3 == (3 - np.linalg.matrix_rank(T313)) + np.linalg.matrix_rank(T313)

well-definedness: T is constant on cosets of U
  ||T(v) - T(v + c u)|| = 0.000e+00
  ||T(v) - T(v + c u)|| = 0.000e+00
  ||T(v) - T(v + c u)|| = 0.000e+00
  ||T(v) - T(v + c u)|| = 0.000e+00
dim V = 3   dim ker T = 1   rank T = 2
images of two coset representatives =
 [[1. 0.]
 [0. 1.]] 
  independent: True
